long_name = 'ToME MCP Bridge'
short_name = 'mcp-bridge'
for_module = 'tome'
version = {1, 7, 6}
addon_version = {0, 9, 0}
weight = 500
author = {'ToME MCP contributors'}
description = [[Expose player-visible state, native actions, growth, inventory, level exits and bounded rest to a local MCP server. Configure tome_mcp_bridge.token before connecting.]]
tags = {'interface', 'mcp'}
overload = true
superload = true
hooks = true
