-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local previous_turnBasedTick=_M.tick
function _M:tick(...)
    local Runtime=require 'mod.mcp_bridge.Runtime'
    if Runtime.holdsNativeInput(self) then
        self.paused=true
        engine.Game.tick(self)
        if Runtime.holdsNativeInput(self) then self.paused=true
        elseif self.player and self.player.energy and self.player.energy.value<self.energy_to_act then
            self.paused=false
        end
        return
    end
    local result=previous_turnBasedTick(self,...)
    if Runtime.holdsNativeInput(self) then self.paused=true end
    return result
end
Compat.register('turnBasedTick',_M.tick,previous_turnBasedTick,'/engine/GameTurnBased.lua','dcf5eb7bf7139fb322e405123f917da0')
return _M
