-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local previous_setSpot=_M.setSpot
Compat.register('setSpot',_M.setSpot,previous_setSpot,'/engine/Target.lua','1c3da402e65829bd7ed7464625da1dc3')
local previous_setDirFrom=_M.setDirFrom
Compat.register('setDirFrom',_M.setDirFrom,previous_setDirFrom,'/engine/Target.lua','1c3da402e65829bd7ed7464625da1dc3')
return _M
