-- GPL-3.0-or-later. Version-pinned auto-combat effect manifest (v2).
--
-- This is the canonical, curated description of what each whitelisted talent
-- actually does: its targeting cursor and every separate damage/detriment
-- component (instant projection, moving projectile, secondary projection and
-- persistent map effect). Each component records its delivery path, footprint,
-- self-/friendly-fire filters and the provenance of every value. The guard
-- consumes these components directly; it never reads a single-shape field.
--
-- Source identity (file hashes and definition lines) is generated by
-- `tools/generate_effect_manifest.py` into `EffectManifestSources.lua` and is
-- checked at load time by `EffectManifestDrift`. A mismatch fails closed with
-- `adapter_source_drift` and never uses stale metadata.
--
-- The module is static data plus pure derived helpers: it never calls the
-- engine, a talent builder or RNG.
local Sources=require 'mod.auto_combat.EffectManifestSources'
local M={}
M.VERSION='tome-auto-combat-adapters/v2'
M.SCHEMA='tome-auto-combat/v1'
M.SOURCES=Sources
M.GAME_VERSION='1.7.6'

-- Provenance vocabulary for resolved filter values.
--   explicit         declared in the talent source
--   target_default   Target:getType default (absent field -> true)
--   cone_default     Target:getType cone transform (forces selffire=false)
--   map_default      Map:addEffect default (absent argument -> true)
--   curated_formula  audited dynamic formula (value can be unknown at runtime)
M.PROVENANCE={EXPLICIT='explicit',TARGET_DEFAULT='target_default',CONE_DEFAULT='cone_default',
    MAP_DEFAULT='map_default',CURATED_FORMULA='curated_formula'}

local TARGET_DEFAULT=M.PROVENANCE.TARGET_DEFAULT
local EXPLICIT=M.PROVENANCE.EXPLICIT
local MAP_DEFAULT=M.PROVENANCE.MAP_DEFAULT
local CURATED=M.PROVENANCE.CURATED_FORMULA

local function selfEntry(kind,resource)
    return {kind=kind,target='self',resource=resource,components={},conformance={builder='none'}}
end

-- Every hostile entry keeps `cursor` (targeting geometry) separate from the
-- damaging components. `conformance` is the subset expected from the real
-- native target builder at the getTarget seam.
M.ENTRIES={
    T_CHANT_OF_FORTRESS=selfEntry('sustain','positive'),
    T_HYMN_OF_SHADOWS=selfEntry('sustain','negative'),
    T_HEALING_LIGHT=selfEntry('heal','positive'),
    T_BARRIER=selfEntry('buff','positive'),
    T_TWILIGHT=selfEntry('buff','negative'),
    T_MOONLIGHT_RAY={kind='attack',target='hostile',resource='negative',range=10,
        cursor={shape='beam',range=10},
        conformance={shape='beam',builder=true},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='beam',range=10,center='target'},
            {id='instant',phase='instant',delivery='project',shape='beam',range=10,center='target',
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
        }},
    T_SEARING_LIGHT={kind='attack',target='hostile',resource='positive',range=7,direct_hit=true,
        cursor={shape='ball',range=7,radius=1},
        conformance={shape='ball',range=7,radius=1,builder=false},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='ball',range=7,radius=1,center='target'},
            {id='instant',phase='instant',delivery='project',shape='hit',range=7,center='target',
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
            {id='ground',phase='ground',delivery='map_effect',shape='ball',center='target',radius=1,duration=4,
                selffire=0,friendlyfire=0,
                provenance={selffire=EXPLICIT,friendlyfire=EXPLICIT}},
        }},
    T_ATTACK={kind='attack',target='hostile',range=1,melee=true,
        cursor={shape='hit',range=1},
        conformance={shape='hit',range=1,builder=true},
        components={
            {id='melee',phase='melee',delivery='attackTarget',shape='hit',range=1,center='target'},
        }},
    T_SUN_BEAM={kind='attack',target='hostile',resource='positive',range=7,
        cursor={shape='hit',range=7},
        conformance={shape='hit',range=7,builder=true},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='hit',range=7,center='target'},
            {id='instant',phase='instant',delivery='project',shape='hit',range=7,center='target',
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
            {id='secondary',phase='secondary',delivery='project',shape='ball',range=7,radius=2,center='target',
                when={kind='talent_level',at_least=3},
                selffire=0,friendlyfire=100,
                provenance={selffire=EXPLICIT,friendlyfire=TARGET_DEFAULT}},
        }},
    T_WEAPON_OF_LIGHT=selfEntry('sustain','positive'),
    -- Flame is a bolt below effective TL5, a beam at/above it, and a radius-1
    -- wide-beam under Thaumaturgy. The wide-beam branch additionally calls
    -- `spellFriendlyFire` for FF (dynamic). The guard uses the branch union
    -- whenever the branch cannot be resolved. Burning Wake adds a source/impact
    -- radius-0 ground zone whose SF is dynamic and whose FF defaults to true.
    T_FLAME={kind='attack',target='hostile',resource='mana',range=10,radius=1,
        cursor={shape='widebeam',range=10,radius=1},
        conformance={shape='widebeam',radius=1,builder=true},
        union={'bolt','beam','widebeam'},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='widebeam',range=10,radius=1,center='target'},
            {id='flame_bolt',phase='instant',delivery='projectile',shape='bolt',range=10,center='target',
                when={kind='talent_level',below=5},
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
            {id='flame_beam',phase='instant',delivery='project',shape='beam',range=10,center='target',
                when={kind='talent_level',at_least=5},
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
            {id='flame_widebeam',phase='instant',delivery='project',shape='widebeam',range=10,radius=1,center='target',
                when={kind='attr',id='archmage_widebeam'},
                selffire=0,friendlyfire='unknown',
                provenance={selffire=EXPLICIT,friendlyfire=CURATED}},
            {id='ground',phase='ground',delivery='map_effect',shape='ball',center='target',radius=0,duration=4,
                per_grid=true,
                when={kind='attr',id='burning_wake'},
                selffire='unknown',friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=MAP_DEFAULT}},
        }},
    T_HEAL=selfEntry('heal','mana'),
    -- Re-admitted dynamic talents (TODO #55). All four expose a `t.target`
    -- builder, so the guard reads the live builder for the instant component
    -- (including its `spellFriendlyFire()` value and dynamic radius). The SF of
    -- the persistent Burning Wake / Shadow Blast ground components is resolved
    -- from the audited `spellFriendlyFire` getter; if that is unavailable the
    -- value is `unknown` and the component fails closed.
    -- Flameshock: source-centred cone (range 0, radius 4..8, explicit
    -- selffire=false) plus an optional source-centred Burning Wake cone
    -- (duration 4, SF spellFriendlyFire, default-true FF).
    T_FLAMESHOCK={kind='attack',target='hostile',resource='mana',range=0,
        cursor={shape='cone'},
        conformance={shape='cone',builder=true},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='cone',center='target'},
            {id='instant',phase='instant',delivery='project',shape='cone',center='target',
                selffire=0,friendlyfire=100,
                provenance={selffire=EXPLICIT,friendlyfire=TARGET_DEFAULT}},
            {id='ground',phase='ground',delivery='map_effect',shape='cone',center='self',direction='target',
                radius={from='target'},
                when={kind='attr',id='burning_wake'},
                duration=4,
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=MAP_DEFAULT}},
        }},
    -- Fireflash: ball projectile (range 7, radius 2..5, player_selffire=true,
    -- dynamic SF) plus an optional impact-centred Burning Wake ball (duration 4,
    -- radius = talent radius, SF = the target spec's SF, default-true FF).
    T_FIREFLASH={kind='attack',target='hostile',resource='mana',range=7,
        cursor={shape='ball',range=7},
        conformance={shape='ball',builder=true},
        components={
            {id='cursor',phase='cursor',delivery='projectile',shape='ball',range=7,center='target'},
            {id='instant',phase='instant',delivery='projectile',shape='ball',range=7,center='target',
                player_selffire=true,
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=TARGET_DEFAULT,player_selffire=EXPLICIT}},
            {id='ground',phase='ground',delivery='map_effect',shape='ball',center='target',
                radius={from='target'},
                when={kind='attr',id='burning_wake'},
                duration=4,
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=MAP_DEFAULT}},
        }},
    -- Shadow Blast: immediate radius-3 ball (dynamic SF, default-true FF) plus a
    -- persistent radius-3 ball (duration up to 9, dynamic SF, default-true FF).
    T_SHADOW_BLAST={kind='attack',target='hostile',resource='negative',range=6,radius=3,
        cursor={shape='ball',range=6,radius=3},
        conformance={shape='ball',radius=3,builder=true},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='ball',range=6,radius=3,center='target'},
            {id='instant',phase='instant',delivery='project',shape='ball',range=6,radius=3,center='target',
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=TARGET_DEFAULT}},
            {id='ground',phase='ground',delivery='map_effect',shape='ball',center='target',radius=3,
                duration=9,
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=MAP_DEFAULT,duration=CURATED}},
        }},
    -- Starfall: immediate ball (radius 1..2, dynamic SF, default-true FF); no
    -- persistent ground component.
    T_STARFALL={kind='attack',target='hostile',resource='negative',range=6,
        cursor={shape='ball',range=6},
        conformance={shape='ball',builder=true},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='ball',range=6,center='target'},
            {id='instant',phase='instant',delivery='project',shape='ball',range=6,center='target',
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=TARGET_DEFAULT}},
        }},
    T_ARCANE_POWER=selfEntry('sustain','mana'),
    T_SHIELDING=selfEntry('sustain','mana'),
    -- Soul Rot builds its bolt inside the action (no `t.target`); the missing
    -- filters normalize to true and the projectile only self-hits with the
    -- player opt-in. Blood Grasp is an explicit self/friendly-safe bolt.
    T_SOUL_ROT={kind='attack',target='hostile',resource='vim',range=10,
        cursor={shape='bolt',range=10},
        conformance={shape='bolt',range=10,builder=false},
        components={
            {id='cursor',phase='cursor',delivery='projectile',shape='bolt',range=10,center='target'},
            {id='instant',phase='projectile',delivery='projectile',shape='bolt',range=10,center='target',
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
        }},
    T_BLOOD_GRASP={kind='attack',target='hostile',resource='vim',range=10,
        cursor={shape='bolt',range=10},
        conformance={shape='bolt',range=10,builder=true},
        components={
            {id='cursor',phase='cursor',delivery='projectile',shape='bolt',range=10,center='target'},
            {id='instant',phase='projectile',delivery='projectile',shape='bolt',range=10,center='target',
                selffire=0,friendlyfire=0,
                provenance={selffire=EXPLICIT,friendlyfire=EXPLICIT}},
        }},
    T_DARK_RITUAL=selfEntry('sustain','vim'),
    T_SHATTERING_BLOW={kind='attack',target='hostile',resource='stamina',range=1,melee=true,
        cursor={shape='hit',range=1},
        conformance={shape='hit',range=1,builder=true},
        components={
            {id='melee',phase='melee',delivery='attackTarget',shape='hit',range=1,center='target'},
        }},
    T_BERSERKER_RAGE=selfEntry('sustain','stamina'),
    -- Daunting Presence is a self sustain, but using it fires a callback that
    -- applies a non-damage debuff in a source-centred radius-6 ball with
    -- friendlyfire=false (SF omitted -> true, so self is safe via FF=0).
    T_DAUNTING_PRESENCE={kind='sustain',target='self',resource='stamina',components={},
        conformance={builder='none'},
        callbacks={
            {id='daunting_pulse',phase='secondary',delivery='project',shape='ball',center='self',radius=6,
                selffire=100,friendlyfire=0,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=EXPLICIT}},
        }},
    T_ADRENALINE_SURGE=selfEntry('buff',nil),
    -- Movement tranche (v1.6). A movement adapter records the exact native
    -- target request and landing classification; MovementPlanner consumes it and
    -- the guard skips it (there is no damage footprint to model for a plain
    -- step or teleport). `landing` values: exact | bounded_alternatives | random
    -- | source_defined. Unknown bounds stay absent (`unknown`), never invented.
    T_RUSH={kind='movement',target='hostile',resource='stamina',
        movement={target_requests={'actor'},delivery='line_move',landing='bounded_alternatives',
            center='actor',traverses=true,relocates_other=false},
        components={},conformance={builder=true}},
    T_SKIRMISHER_CUNNING_ROLL={kind='movement',target='grid',resource='stamina',
        movement={target_requests={'grid'},delivery='line_move',landing='exact',
            center='requested_grid',traverses=true,relocates_other=false},
        components={},conformance={builder=true}},
    T_PHASE_DOOR={kind='movement',target='self',resource='mana',
        movement={target_requests={'none'},delivery='teleport',landing='random',
            center='self',radius=6,min_radius=1,
            -- The no-prompt form is the only form this adapter drives. TL4+
            -- branches to a target prompt and TL5 to a landing prompt; those
            -- variants are published as unsupported with the same typed reason
            -- the runtime rejects them with (MFT-REV-03/08).
            unsupported_variants={{at_least=4,scope='effective_talent_level>=4',
                missing='actor_then_grid_target_plan',
                reason='Phase Door prompts for a target at TL4+ and a landing at TL5; the executor pre-fills one native prompt only'}}},
        components={},conformance={builder=false}},
}

-- Attach the generated source identity to every entry so a component can
-- carry its provenance without a second lookup. Static data; no engine access.
for talent,entry in pairs(M.ENTRIES) do entry.source=Sources.talents[talent] end
function M.source(talent) return Sources.talents[talent] end

-- Structured capability gaps (MFT-REV-08): talent, level/variant scope, the
-- missing adapter capability and the reason. Published through `summary()` so a
-- caller gets a typed reason rather than prose. These are ordinary movement
-- actions whose adapters are not yet source-reviewed; they are not strategy
-- refusals and do not affect already-supported actions.
M.UNSUPPORTED={
    {talent='T_PHASE_DOOR',scope='effective_talent_level>=4',
        missing='actor_then_grid_target_plan',
        reason='the no-prompt random self teleport is driven; target/landing prompts are not'},
    {talent='T_BLINK_RUNE',scope='any',missing='source_reviewed_movement_adapter',
        reason='visible grid request with a random fallback; adapter not source-reviewed'},
    {talent='T_SKIRMISHER_VAULT',scope='any',missing='source_reviewed_movement_adapter',
        reason='grid landing plus a visible adjacent launch actor; adapter not source-reviewed'},
    {talent='T_DIMENSIONAL_STEP',scope='any',missing='source_reviewed_movement_adapter',
        reason='requested-grid teleport with a possible actor swap; adapter not source-reviewed'},
    {talent='T_SHADOWSTEP',scope='any',missing='source_reviewed_movement_adapter',
        reason='actor-anchored random teleport plus an attack; adapter not source-reviewed'},
    {talent='T_GIANT_LEAP',scope='any',missing='source_reviewed_movement_adapter',
        reason='requested-grid movement with an alternate landing and radius effect; adapter not source-reviewed'},
    {talent='T_DISPLACEMENT_SHIELD',scope='any',missing='source_reviewed_effect_adapter',
        reason='actor-target shield that does not relocate the player; effect adapter not source-reviewed'},
    {talent='*',scope='any',missing='moving_or_swapping_another_actor',
        reason='typed multi-actor destination/effect semantics are not implemented'},
}

function M.entry(talent) return M.ENTRIES[talent] end
function M.supported(talent) return talent~=nil and M.ENTRIES[talent]~=nil end
function M.isSustain(talent)
    local entry=M.ENTRIES[talent]
    return entry~=nil and entry.kind=='sustain'
end

-- Components that can affect an actor, in evaluation order (ground last).
function M.effectComponents(entry)
    local out={}
    for _,component in ipairs(entry and entry.components or {}) do
        if component.phase~='cursor' then out[#out+1]=component end
    end
    return out
end

-- Distinct conditional variants declared by an entry: `{when, components}`.
function M.variants(entry)
    local groups={}
    for _,component in ipairs(entry and entry.components or {}) do
        local key=component.when and (component.when.kind..':'..tostring(component.when.id or component.when.at_least or component.when.below)) or 'always'
        local group=groups[key]
        if not group then
            group={when=component.when or {kind='always'},components={}}
            groups[key]=group
            groups[#groups+1]=group
        end
        group.components[#group.components+1]=component
    end
    return groups
end

-- Public capability summary, derived from the canonical components so it can
-- never disagree with the guard's source of truth.
function M.summary()
    local talents={}
    for talent,entry in pairs(M.ENTRIES) do
        local compat=M.compat(entry)
        talents[#talents+1]={talent=talent,kind=entry.kind,target=entry.target,
            delivery=compat.delivery,shape=compat.shape,range=compat.range,radius=compat.radius,
            resource=entry.resource,selffire=compat.selffire,friendlyfire=compat.friendlyfire,
            friendlyfire_risk=compat.friendlyfire_risk,
            has_ground=compat.ground~=nil,has_secondary=compat.secondary~=nil}
    end
    table.sort(talents,function(a,b) return a.talent<b.talent end)
    return {schema=M.SCHEMA,adapter_version=M.VERSION,game_version=M.GAME_VERSION,
        source_schema=Sources.schema,unsupported=M.UNSUPPORTED,talents=talents}
end

-- Derived compatibility view: a conservative flattening of the canonical
-- components for capability reporting and validators. It is never the guard's
-- input. `M.compat(entry)` guarantees the summary and validators agree with
-- the components.
local SHAPE_ORDER={widebeam=6,cone=5,ball=4,beam=3,bolt=2,hit=1,melee=0}
function M.compat(entry)
    if not entry then return nil end
    local primary
    local shape,delivery,selffire,friendlyfire
    local ground,secondary
    for _,component in ipairs(entry.components or {}) do
        if component.phase=='ground' then ground=component end
        if component.phase=='secondary' then secondary=component end
        if component.phase=='instant' or component.phase=='projectile' or component.phase=='melee' then
            if not primary then primary=component end
            local order=SHAPE_ORDER[component.shape] or 0
            if not shape or order>(SHAPE_ORDER[shape] or 0) then shape=component.shape end
            if component.delivery=='projectile' then delivery='projectile'
            elseif component.delivery=='attackTarget' then delivery=delivery or 'attackTarget'
            elseif not delivery then delivery='project' end
            local sf=component.selffire
            if type(sf)=='table' then sf='unknown' end
            if sf~=nil and (selffire==nil or (tonumber(sf) or 100)>(tonumber(selffire) or 0)) then selffire=sf end
            local ff=component.friendlyfire
            if type(ff)=='table' then ff='unknown' end
            if ff~=nil and (friendlyfire==nil or (tonumber(ff) or 100)>(tonumber(friendlyfire) or 0)) then friendlyfire=ff end
        end
    end
    local risk='none'
    if selffire~=0 or friendlyfire~=0 then
        if shape=='beam' or shape=='bolt' or shape=='widebeam' then risk='line'
        elseif shape=='ball' or shape=='cone' then risk='area' end
    end
    return {shape=shape,delivery=delivery,range=entry.range,radius=entry.radius,
        selffire=selffire or 0,friendlyfire=friendlyfire or 0,friendlyfire_risk=risk,
        cursor=entry.cursor,ground=ground,secondary=secondary,union=entry.union,
        components=entry.components,primary=primary}
end

M.HOSTILE_SELECTORS={nearest_hostile=true,lowest_hp_hostile=true,
    highest_rank_hostile=true,most_dangerous_hostile=true}
M.SELF_SELECTORS={self=true}
M.ACTIONS={
    use_talent={kind='talent'},
    attack={kind='attack'},
    move={kind='movement',action='move'},
    wait={kind='utility'},
    rest={kind='native_activity',activity='rest',default_max_turns=1000},
    auto_explore={kind='native_activity',activity='auto_explore'},
    change_level={kind='native_activity',activity='change_level',default_enabled=false},
}
function M.actionSupported(action) return action~=nil and M.ACTIONS[action]~=nil end

function M.verify(policy)
    local errors={}
    for index,rule in ipairs((policy and policy.rules) or {}) do
        local action=rule['then'] and rule['then'].action
        local path='rules['..index..']'
        if action~=nil and not M.ACTIONS[action] then
            errors[#errors+1]={path=path..'.then.action',code='unsupported_action'}
        end
        local entry=rule['then'] and rule['then'].talent and M.ENTRIES[rule['then'].talent] or nil
        if entry then
            local selector=rule['then'].target or (policy.targeting and policy.targeting.default)
            -- MFT-REV-03 (Option A): an actor step selector is the effective
            -- binding when the action/default selector is absent, so the
            -- self/hostile consistency check honours it.
            if selector==nil and type(rule['then'].target_plan)=='table' then
                for _,step in ipairs(rule['then'].target_plan) do
                    if step.request=='actor' and step.selector~=nil then
                        selector=step.selector
                        break
                    end
                end
            end
            -- A no-target movement request (position/relative/native_random) needs
            -- no actor selector; the plugin must not invent a self requirement.
            local destination=rule['then'].destination
            local no_target_move=entry.kind=='movement' and type(destination)=='table'
                and (destination.selector=='position' or destination.selector=='relative'
                    or destination.selector=='native_random')
            if entry.target=='self' and selector~=nil and not M.SELF_SELECTORS[selector]
                and not no_target_move then
                errors[#errors+1]={path=path,code='selector_not_self_only',talent=rule['then'].talent}
            end
            if entry.target=='hostile' and selector~=nil and not M.HOSTILE_SELECTORS[selector]
                and not no_target_move then
                errors[#errors+1]={path=path,code='selector_not_hostile',talent=rule['then'].talent}
            end
            -- MFT-REV-03: an explicit ordered target plan must match the
            -- source-pinned movement adapter's request sequence exactly.
            local plan=rule['then'].target_plan
            local movement=entry.kind=='movement' and entry.movement or nil
            if type(plan)=='table' then
                if not (movement and type(movement.target_requests)=='table') then
                    errors[#errors+1]={path=path..'.then.target_plan',code='target_plan_not_supported',
                        talent=rule['then'].talent}
                else
                    local expected=movement.target_requests
                    if #plan~=#expected then
                        errors[#errors+1]={path=path..'.then.target_plan',code='target_plan_mismatch',
                            expected=table.concat(expected,','),got=#plan}
                    else
                        for step=1,#plan do
                            if plan[step].request~=expected[step] then
                                errors[#errors+1]={path=path..'.then.target_plan['..step..']',
                                    code='target_plan_mismatch',expected=expected[step],
                                    got=plan[step].request}
                            elseif expected[step]=='actor' and plan[step].selector~=nil
                                and selector~=nil and plan[step].selector~=selector then
                                -- MFT-REV-03: an actor step selector must agree with
                                -- the action binding; contradictory data is not
                                -- silently discarded.
                                errors[#errors+1]={path=path..'.then.target_plan['..step..'].selector',
                                    code='target_plan_selector_mismatch',
                                    expected=selector,got=plan[step].selector}
                            end
                        end
                    end
                end
            end
        elseif rule['then'] and rule['then'].action=='use_talent' then
            errors[#errors+1]={path=path,code='unsupported_talent',talent=rule['then'].talent}
        end
    end
    for index,sustain in ipairs((policy and policy.sustains) or {}) do
        if not M.isSustain(sustain.talent) then
            errors[#errors+1]={path='sustains['..index..']',code='not_a_sustain',talent=sustain.talent}
        end
    end
    if #errors==0 then return true end
    return nil,errors
end

return M
