-- GPL-3.0-or-later. Version-pinned auto-combat effect manifest (v2).
--
-- This is the canonical, curated description of what each whitelisted talent
-- actually does: its targeting cursor and every separate damage/detriment
-- component (instant projection, moving projectile, secondary projection and
-- persistent map effect). Each component records its delivery path, footprint,
-- self-/friendly-fire filters and the provenance of every value. The guard
-- consumes these components directly; it never reads a single-shape field.
--
-- Source identity (file hashes and definition lines) is generated by
-- `tools/generate_effect_manifest.py` into `EffectManifestSources.lua`. Under
-- the no-strict-audit principle it is **advisory re-review metadata only**
-- (`EffectManifestDrift.telemetry`); it never gates a decision. The guard calls
-- the live builders/getters directly and fails closed only on an unavailable or
-- unusable value (typed derivation-unknown).
--
-- The module is static data plus pure derived helpers: it never calls the
-- engine, a talent builder or RNG.
local Sources=require 'mod.auto_combat.EffectManifestSources'
local Json=require 'mod.mcp_bridge.Json'
local Factory=require 'mod.auto_combat.MovementAdapterFactory'
local M={}
M.VERSION='tome-auto-combat-adapters/v2'
M.SCHEMA='tome-auto-combat/v1'
M.SOURCES=Sources
M.GAME_VERSION='1.7.6'

-- Provenance vocabulary for resolved filter values.
--   explicit         declared in the talent source
--   target_default   Target:getType default (absent field -> true)
--   cone_default     Target:getType cone transform (forces selffire=false)
--   map_default      Map:addEffect default (absent argument -> true)
--   curated_formula  audited dynamic formula (value can be unknown at runtime)
M.PROVENANCE={EXPLICIT='explicit',TARGET_DEFAULT='target_default',CONE_DEFAULT='cone_default',
    MAP_DEFAULT='map_default',CURATED_FORMULA='curated_formula'}

local TARGET_DEFAULT=M.PROVENANCE.TARGET_DEFAULT
local EXPLICIT=M.PROVENANCE.EXPLICIT
local MAP_DEFAULT=M.PROVENANCE.MAP_DEFAULT
local CURATED=M.PROVENANCE.CURATED_FORMULA

local function selfEntry(kind,resource)
    return {kind=kind,target='self',resource=resource,components={},conformance={builder='none'}}
end

-- Static manifest construction must fail loudly on a malformed declaration
-- instead of silently storing a nil entry. `Factory.expand`/`matrix` return a
-- typed error; these wrappers turn that into a load-time error.
local function movementAdapter(template,params)
    return Factory.expandOrError(template,params)
end
local function movementMatrix(branches,axes)
    local movement,err=Factory.matrix(branches,axes)
    if not movement then
        error('movement adapter matrix failed: '..tostring(err and (err.detail or err.reason)),2)
    end
    return movement
end

-- Every hostile entry keeps `cursor` (targeting geometry) separate from the
-- damaging components. `conformance` is the subset expected from the real
-- native target builder at the getTarget seam.
M.ENTRIES={
    T_CHANT_OF_FORTRESS=selfEntry('sustain','positive'),
    T_HYMN_OF_SHADOWS=selfEntry('sustain','negative'),
    T_HEALING_LIGHT=selfEntry('heal','positive'),
    T_BARRIER=selfEntry('buff','positive'),
    T_TWILIGHT=selfEntry('buff','negative'),
    T_MOONLIGHT_RAY={kind='attack',target='hostile',resource='negative',range=10,
        cursor={shape='beam',range=10},
        conformance={shape='beam',builder=true},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='beam',range=10,center='target'},
            {id='instant',phase='instant',delivery='project',shape='beam',range=10,center='target',
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
        }},
    T_SEARING_LIGHT={kind='attack',target='hostile',resource='positive',range=7,direct_hit=true,
        cursor={shape='ball',range=7,radius=1},
        conformance={shape='ball',range=7,radius=1,builder=false},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='ball',range=7,radius=1,center='target'},
            {id='instant',phase='instant',delivery='project',shape='hit',range=7,center='target',
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
            {id='ground',phase='ground',delivery='map_effect',shape='ball',center='target',radius=1,duration=4,
                selffire=0,friendlyfire=0,
                provenance={selffire=EXPLICIT,friendlyfire=EXPLICIT}},
        }},
    T_ATTACK={kind='attack',target='hostile',range=1,melee=true,
        cursor={shape='hit',range=1},
        conformance={shape='hit',range=1,builder=true},
        components={
            {id='melee',phase='melee',delivery='attackTarget',shape='hit',range=1,center='target'},
        }},
    T_SUN_BEAM={kind='attack',target='hostile',resource='positive',range=7,
        cursor={shape='hit',range=7},
        conformance={shape='hit',range=7,builder=true},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='hit',range=7,center='target'},
            {id='instant',phase='instant',delivery='project',shape='hit',range=7,center='target',
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
            {id='secondary',phase='secondary',delivery='project',shape='ball',range=7,radius=2,center='target',
                when={kind='talent_level',at_least=3},
                selffire=0,friendlyfire=100,
                provenance={selffire=EXPLICIT,friendlyfire=TARGET_DEFAULT}},
        }},
    T_WEAPON_OF_LIGHT=selfEntry('sustain','positive'),
    -- Flame is a bolt below effective TL5, a beam at/above it, and a radius-1
    -- wide-beam under Thaumaturgy. The wide-beam branch additionally calls
    -- `spellFriendlyFire` for FF (dynamic). The guard uses the branch union
    -- whenever the branch cannot be resolved. Burning Wake adds a source/impact
    -- radius-0 ground zone whose SF is dynamic and whose FF defaults to true.
    T_FLAME={kind='attack',target='hostile',resource='mana',range=10,radius=1,
        cursor={shape='widebeam',range=10,radius=1},
        conformance={shape='widebeam',radius=1,builder=true},
        union={'bolt','beam','widebeam'},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='widebeam',range=10,radius=1,center='target'},
            {id='flame_bolt',phase='instant',delivery='projectile',shape='bolt',range=10,center='target',
                when={kind='talent_level',below=5},
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
            {id='flame_beam',phase='instant',delivery='project',shape='beam',range=10,center='target',
                when={kind='talent_level',at_least=5},
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
            {id='flame_widebeam',phase='instant',delivery='project',shape='widebeam',range=10,radius=1,center='target',
                when={kind='attr',id='archmage_widebeam'},
                selffire=0,friendlyfire='unknown',
                provenance={selffire=EXPLICIT,friendlyfire=CURATED}},
            {id='ground',phase='ground',delivery='map_effect',shape='ball',center='target',radius=0,duration=4,
                per_grid=true,
                when={kind='attr',id='burning_wake'},
                selffire='unknown',friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=MAP_DEFAULT}},
        }},
    T_HEAL=selfEntry('heal','mana'),
    -- Re-admitted dynamic talents (TODO #55). All four expose a `t.target`
    -- builder, so the guard reads the live builder for the instant component
    -- (including its `spellFriendlyFire()` value and dynamic radius). The SF of
    -- the persistent Burning Wake / Shadow Blast ground components is resolved
    -- from the audited `spellFriendlyFire` getter; if that is unavailable the
    -- value is `unknown` and the component fails closed.
    -- Flameshock: source-centred cone (range 0, radius 4..8, explicit
    -- selffire=false) plus an optional source-centred Burning Wake cone
    -- (duration 4, SF spellFriendlyFire, default-true FF).
    T_FLAMESHOCK={kind='attack',target='hostile',resource='mana',range=0,
        cursor={shape='cone'},
        conformance={shape='cone',builder=true},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='cone',center='target'},
            {id='instant',phase='instant',delivery='project',shape='cone',center='target',
                selffire=0,friendlyfire=100,
                provenance={selffire=EXPLICIT,friendlyfire=TARGET_DEFAULT}},
            {id='ground',phase='ground',delivery='map_effect',shape='cone',center='self',direction='target',
                radius={from='target'},
                when={kind='attr',id='burning_wake'},
                duration=4,
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=MAP_DEFAULT}},
        }},
    -- Fireflash: ball projectile (range 7, radius 2..5, player_selffire=true,
    -- dynamic SF) plus an optional impact-centred Burning Wake ball (duration 4,
    -- radius = talent radius, SF = the target spec's SF, default-true FF).
    T_FIREFLASH={kind='attack',target='hostile',resource='mana',range=7,
        cursor={shape='ball',range=7},
        conformance={shape='ball',builder=true},
        components={
            {id='cursor',phase='cursor',delivery='projectile',shape='ball',range=7,center='target'},
            {id='instant',phase='instant',delivery='projectile',shape='ball',range=7,center='target',
                player_selffire=true,
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=TARGET_DEFAULT,player_selffire=EXPLICIT}},
            {id='ground',phase='ground',delivery='map_effect',shape='ball',center='target',
                radius={from='target'},
                when={kind='attr',id='burning_wake'},
                duration=4,
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=MAP_DEFAULT}},
        }},
    -- Shadow Blast: immediate radius-3 ball (dynamic SF, default-true FF) plus a
    -- persistent radius-3 ball (duration up to 9, dynamic SF, default-true FF).
    T_SHADOW_BLAST={kind='attack',target='hostile',resource='negative',range=6,radius=3,
        cursor={shape='ball',range=6,radius=3},
        conformance={shape='ball',radius=3,builder=true},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='ball',range=6,radius=3,center='target'},
            {id='instant',phase='instant',delivery='project',shape='ball',range=6,radius=3,center='target',
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=TARGET_DEFAULT}},
            {id='ground',phase='ground',delivery='map_effect',shape='ball',center='target',radius=3,
                duration=9,
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=MAP_DEFAULT,duration=CURATED}},
        }},
    -- Starfall: immediate ball (radius 1..2, dynamic SF, default-true FF); no
    -- persistent ground component.
    T_STARFALL={kind='attack',target='hostile',resource='negative',range=6,
        cursor={shape='ball',range=6},
        conformance={shape='ball',builder=true},
        components={
            {id='cursor',phase='cursor',delivery='project',shape='ball',range=6,center='target'},
            {id='instant',phase='instant',delivery='project',shape='ball',range=6,center='target',
                selffire={dynamic='spellFriendlyFire'},friendlyfire=100,
                provenance={selffire=CURATED,friendlyfire=TARGET_DEFAULT}},
        }},
    T_ARCANE_POWER=selfEntry('sustain','mana'),
    T_SHIELDING=selfEntry('sustain','mana'),
    -- Soul Rot builds its bolt inside the action (no `t.target`); the missing
    -- filters normalize to true and the projectile only self-hits with the
    -- player opt-in. Blood Grasp is an explicit self/friendly-safe bolt.
    T_SOUL_ROT={kind='attack',target='hostile',resource='vim',range=10,
        cursor={shape='bolt',range=10},
        conformance={shape='bolt',range=10,builder=false},
        components={
            {id='cursor',phase='cursor',delivery='projectile',shape='bolt',range=10,center='target'},
            {id='instant',phase='projectile',delivery='projectile',shape='bolt',range=10,center='target',
                selffire=100,friendlyfire=100,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=TARGET_DEFAULT}},
        }},
    T_BLOOD_GRASP={kind='attack',target='hostile',resource='vim',range=10,
        cursor={shape='bolt',range=10},
        conformance={shape='bolt',range=10,builder=true},
        components={
            {id='cursor',phase='cursor',delivery='projectile',shape='bolt',range=10,center='target'},
            {id='instant',phase='projectile',delivery='projectile',shape='bolt',range=10,center='target',
                selffire=0,friendlyfire=0,
                provenance={selffire=EXPLICIT,friendlyfire=EXPLICIT}},
        }},
    T_DARK_RITUAL=selfEntry('sustain','vim'),
    T_SHATTERING_BLOW={kind='attack',target='hostile',resource='stamina',range=1,melee=true,
        cursor={shape='hit',range=1},
        conformance={shape='hit',range=1,builder=true},
        components={
            {id='melee',phase='melee',delivery='attackTarget',shape='hit',range=1,center='target'},
        }},
    T_BERSERKER_RAGE=selfEntry('sustain','stamina'),
    -- Daunting Presence is a self sustain, but using it fires a callback that
    -- applies a non-damage debuff in a source-centred radius-6 ball with
    -- friendlyfire=false (SF omitted -> true, so self is safe via FF=0).
    T_DAUNTING_PRESENCE={kind='sustain',target='self',resource='stamina',components={},
        conformance={builder='none'},
        callbacks={
            {id='daunting_pulse',phase='secondary',delivery='project',shape='ball',center='self',radius=6,
                selffire=100,friendlyfire=0,
                provenance={selffire=TARGET_DEFAULT,friendlyfire=EXPLICIT}},
        }},
    T_ADRENALINE_SURGE=selfEntry('buff',nil),
    -- Movement tranche (v1.6). A movement adapter records the exact native
    -- target request and landing classification; MovementPlanner consumes it and
    -- the guard skips it (there is no damage footprint to model for a plain
    -- step or teleport). `landing` values: exact | bounded_alternatives | random
    -- | source_defined. Unknown bounds stay absent (`unknown`), never invented.
    --
    -- S1 factory: every admitted entry is expanded by the closed
    -- `MovementAdapterFactory` from a source-reviewed template plus explicit
    -- per-talent parameters. The factory only removes boilerplate; it never
    -- scans the game. State variants (Phase Door, Dimensional Step) are closed
    -- matrices resolved at plan time by `MovementAdapterFactory.resolveVariant`.
    T_RUSH={kind='movement',target='hostile',resource='stamina',
        movement=movementAdapter('actor_charge',{
            builder_shape='bolt',
            landing_proof='the action computes the last legal line cell before the bound actor'}),
        components={},conformance={builder=true}},
    T_SKIRMISHER_CUNNING_ROLL={kind='movement',target='grid',resource='stamina',
        movement=movementAdapter('grid_move_exact',{delivery='line_move',traverses=true,
            builder_shape='beam',
            landing_proof='forces the exact requested grid after native blocked/projection checks'}),
        components={},conformance={builder=true}},
    T_SKIRMISHER_VAULT={kind='movement',target='grid',resource='stamina',
        movement=movementAdapter('grid_move_exact',{delivery='leap',traverses=false,
            builder_shape='beam',
            landing_proof='forces the exact requested grid after launch/blocked/projection checks'}),
        components={},conformance={builder=true}},
    -- S2-R4-01: the agility Vault (techniques/agility.lua:83-150, T_VAULT) is
    -- deliberately NOT published here. Its two prompts are distinguishable
    -- (hit-without-nolock then hit+nolock), but the talent is MIXED: the first
    -- (actor) prompt's target is attacked (agility.lua:137-138) and may be dazed
    -- (:140-145) before the move (:149-150). Publishing it as component-free grid
    -- movement with `traverses=true` let a valid policy bind that actor prompt to
    -- `self` and aim an offensive native action at the player, with the
    -- damage/daze invisible to the guard (which skips every movement entry); the
    -- `traverses=true` metadata was also wrong (the native moves directly with
    -- `self:move(x,y,true)`). It is declared in `M.UNSUPPORTED` with the typed
    -- reason `movement_effect_composition_required` until the S3 composition slice
    -- represents and guards the component. (T_SKIRMISHER_VAULT above is a
    -- DIFFERENT talent: the acrobatics Vault, a genuine single-prompt beam
    -- landing — unaffected.)
    -- Dimensional Step: below effective TL5 the native action is always the
    -- self-only `teleportRandom(x,y,0)` branch. At TL5 it swaps only when the
    -- requested grid holds an actor; a player-known empty grid still runs the
    -- non-swap branch, so occupancy is resolved at plan time from player-known
    -- information (`MovementAdapterFactory.resolveOccupancy`). No hidden actor
    -- is inspected.
    T_DIMENSIONAL_STEP={kind='movement',target='grid',resource='paradox',
        movement=movementMatrix({
            {when={kind='talent_level',below=5},template='grid_move_bounded',
                params={delivery='teleport',traverses=false,radius=5,min_radius=0,
                    builder_shape='hit',
                    landing_proof='teleportRandom(x,y,0) falls back to findFreeGrid radius 5'}},
            {when={kind='talent_level',at_least=5},template='grid_move_bounded',
                params={delivery='teleport',traverses=false,radius=5,min_radius=0,
                    builder_shape='hit',occupancy_dependent=true,
                    landing_proof='TL5 occupancy-dependent: an empty grid is the same non-swap teleport; an occupied grid is the S4 swap gap'}},
        }),
        components={},conformance={builder=true}},
    -- Phase Door's prompt program depends on effective level AND the
    -- `phase_door_force_precise` attribute. The old level-only gate was wrong:
    -- the grid prompt appears below TL4 when that attribute is set. Both axes
    -- are pre-read (matrix `axes`), so an unknown level or attribute is
    -- `movement_variant_unknown` even at TL4+. From effective TL4 the action
    -- prompts for a subject (`{'actor'}`) and, at TL5 or under the precise
    -- attribute, for a landing grid (`{'actor','grid'}`): those cells are S2
    -- `request_then_landing` ordered prompt programs (design §4.4).
    --
    -- The TL4 cell is split into two explicit attribute branches rather than
    -- declaring the grid entry `optional=true` (both forms are admitted by
    -- §4.4/§12.1(a); the design recommends the split). Reasons: (1) the
    -- `phase_door_force_precise` axis is already read and must be known at TL4+,
    -- so the two states are already distinguishable; (2) an explicit N=1 branch
    -- keeps the declared program exactly what the source raises, instead of a
    -- second entry the executor must tolerate as missing; (3) the TL5+ cell is
    -- then statically unconditional (`at_least=5`), matching the source's first
    -- disjunct. The trailing-`optional` rule is still implemented and tested
    -- (`MovementAdapterFactory.normalizeRequestSequence`, executor `reduced`),
    -- for genuinely state-dependent trailing prompts.
    T_PHASE_DOOR={kind='movement',target='self',resource='mana',
        movement=movementMatrix({
            {when={kind='all',conditions={
                    {kind='talent_level',below=4},
                    {kind='attr',id='phase_door_force_precise',truthy=false}}},
                template='self_random_teleport',
                params={radius={getter='getRange'},range={getter='getRange'},min_radius=0,
                    landing_proof='no prompt below effective TL4 without phase_door_force_precise'}},
            {when={kind='all',conditions={
                    {kind='talent_level',below=4},
                    {kind='attr',id='phase_door_force_precise',truthy=true}}},
                template='grid_move_bounded',
                params={delivery='teleport',traverses=false,radius={getter='getRadius'},
                    range={getter='getRange'},min_radius=0,
                    fallback_center='self',fallback_radius={getter='getRange'},fallback_when='los_fizzle',
                    landing_proof='grid prompt below TL4 under the precise attribute'}},
            -- Effective TL4 without the precise attribute: the actor prompt only;
            -- the landing is the native random self teleport with `t.getRange`.
            {when={kind='all',conditions={
                    {kind='talent_level',at_least=4,below=5},
                    {kind='attr',id='phase_door_force_precise',truthy=false}}},
                template='request_then_landing',
                params={delivery='teleport',landing='random',center='self',
                    traverses=false,relocates_other=false,
                    radius={getter='getRange'},min_radius=0,range={getter='getRange'},
                    request_sequence={{index=1,request='actor',subject='self',
                        observed={cursor_type='hit',friendlyblock=false,nowarning=true,default_target='self'}}},
                    landing_proof='TL4 actor prompt then teleportRandom(self, getRange)'}},
            -- Effective TL4 with the precise attribute: actor prompt then the
            -- landing grid prompt, landing bounded around the requested grid.
            {when={kind='all',conditions={
                    {kind='talent_level',at_least=4,below=5},
                    {kind='attr',id='phase_door_force_precise',truthy=true}}},
                template='request_then_landing',
                params={delivery='teleport',landing='random',center='requested_grid',
                    traverses=false,relocates_other=false,
                    radius={getter='getRadius'},min_radius=0,range={getter='getRange'},
                    fallback_center='self',fallback_radius={getter='getRange'},fallback_when='los_fizzle',
                    request_sequence={{index=1,request='actor',subject='self',
                            observed={cursor_type='hit',friendlyblock=false,nowarning=true,default_target='self'}},
                        {index=2,request='grid',subject='self',value_source='target_plan',
                            landing_from='envelope',observed={cursor_type='ball',nolock=true,pass_terrain=true,nowarning=true}}},
                    landing_proof='TL4 precise: actor prompt then the landing grid prompt'}},
            -- Effective TL5+: the grid prompt is statically unconditional (the
            -- first disjunct of the native gate is true for this very level read).
            {when={kind='talent_level',at_least=5},
                template='request_then_landing',
                params={delivery='teleport',landing='random',center='requested_grid',
                    traverses=false,relocates_other=false,
                    radius={getter='getRadius'},min_radius=0,range={getter='getRange'},
                    fallback_center='self',fallback_radius={getter='getRange'},fallback_when='los_fizzle',
                    request_sequence={{index=1,request='actor',subject='self',
                            observed={cursor_type='hit',friendlyblock=false,nowarning=true,default_target='self'}},
                        {index=2,request='grid',subject='self',value_source='target_plan',
                            landing_from='envelope',observed={cursor_type='ball',nolock=true,pass_terrain=true,nowarning=true}}},
                    landing_proof='TL5+: actor prompt then the unconditional landing grid prompt'}},
        },{{kind='attr',id='phase_door_force_precise'}}),
        components={},conformance={builder=false}},
}

-- Attach the generated source identity to every entry so a component can
-- carry its provenance without a second lookup. Static data; no engine access.
for talent,entry in pairs(M.ENTRIES) do entry.source=Sources.talents[talent] end
function M.source(talent) return Sources.talents[talent] end

-- Structured capability gaps (MFT-REV-08): talent, level/variant scope, the
-- missing adapter capability and the reason. Published through `summary()` so a
-- caller gets a typed reason rather than prose. These are ordinary movement
-- actions whose adapters are not yet source-reviewed; they are not strategy
-- refusals and do not affect already-supported actions.
M.UNSUPPORTED={
    {talent='T_BLINK_RUNE',scope='any',missing='stable_native_talent_id',
        reason='the native inscription id is slot-indexed (T_RUNE:_BLINK_1..6); no single stable id to source-pin'},
    {talent='T_DIMENSIONAL_STEP',scope='effective_talent_level>=5 and requested_grid_occupied',
        missing='moving_or_swapping_another_actor',
        reason='a player-known empty requested grid uses the admitted non-swap teleport; a known occupied grid is the typed S4 swap gap; unknown occupancy fails closed'},
    {talent='T_SHADOWSTEP',scope='any',missing='source_reviewed_movement_adapter',
        reason='actor-anchored random teleport plus an attack; movement/effect composition is a later slice'},
    {talent='T_GIANT_LEAP',scope='any',missing='source_reviewed_movement_adapter',
        reason='requested-grid movement with an alternate landing and radius effect; movement/effect composition is a later slice'},
    -- S2-R4-01: the agility Vault is a MIXED talent whose sequence is
    -- distinguishable but whose first (actor) prompt's target is attacked and may
    -- be dazed before the move. Component-free grid-movement admission would let
    -- a policy bind that actor prompt to `self` and hide the offensive effect from
    -- the guard. The typed reason reserves it for the S3 composition slice.
    {talent='T_VAULT',scope='any',missing='movement_effect_composition_required',
        reason='mixed movement/effect talent: the first (actor) prompt target is attacked (techniques/agility.lua:137-138) and may be dazed (:140-145) before the move (:149-150); component-free movement admission would bind that actor prompt and hide the effect from the guard'},
    {talent='T_DISPLACEMENT_SHIELD',scope='any',missing='source_reviewed_effect_adapter',
        reason='actor-target shield that does not relocate the player; effect adapter not source-reviewed'},
    -- S2-R3-01 rev5: the officially-decided multi-prompt unsupported set. Each
    -- entry carries its own typed reason (never a strategy judgement); the
    -- survey of every official 1.7.6 multi-prompt talent backs the disposition.
    -- Loop 38 audit (unsupported-audit.md §2.3): the disposition stands — these
    -- are multi-actor effects — but the old `signature_not_distinguishable`
    -- reason was factually wrong: the second spec differs by the ALLOWLISTED
    -- `pass_terrain=true` in both talents (advanced-shadowmancy.lua:45/:82) plus
    -- `friendlyblock=false` for Stone (:82), so the signature axis is not the
    -- blocker and must not be "fixed" by extending the allowlist.
    {talent='T_MERGE',scope='any',missing='moving_or_swapping_another_actor',
        reason='the effect targets another actor: the first prompt is the caster\'s own doomed shadow and Merge kills it (cursed/advanced-shadowmancy.lua:51 target.die(target)) before acting on the second actor (:52); multi-actor semantics are a typed capability gap — the prompts differ by the allowlisted pass_terrain flag, so the signature is not the blocker'},
    {talent='T_STONE',scope='any',missing='moving_or_swapping_another_actor',
        reason='the effect moves another actor: Stone relocates the doomed shadow to the requested grid (cursed/advanced-shadowmancy.lua:88 target:move(sx,sy,true)) and attacks through it (:100 target:project(...)); multi-actor semantics are a typed capability gap — the second spec differs by the allowlisted pass_terrain=true and friendlyblock=false flags, so the signature is not the blocker'},
    -- Loop 38 audit (unsupported-audit.md §2.4): the prompt count is NOT the
    -- blocker — it is player-known and capped at 4 (cursed/shadows.lua:350-352).
    -- The real blocker is the per-iteration random subject.
    {talent='T_CURSED_BOLT',scope='any',missing='nondeterministic_prompt_subject',
        reason='each loop iteration picks a random shadow as the bolt origin (cursed/advanced-shadowmancy.lua:242 rng.table(shadows)) and the entry is order-sensitive: the first failure aborts (:255-258) and the first success consumes the crit roll (:248-251); the prompt count itself is bounded and player-known, so it is not the blocker'},
    -- Loop 38 audit (unsupported-audit.md §2.5): the two prompts ARE
    -- distinguishable by cursor_type (:144 bolt vs :152 hit) and the distance>=2
    -- relation is expressible pre-commit over the two planned grids; the real
    -- blocker is that activation moves nobody and creates a pair of
    -- later-triggered traps with a third-party trigger.
    {talent='T_WORMHOLE',scope='any',missing='effect_is_a_later_triggered_trap_pair',
        reason='activation moves nobody: the talent creates a pair of traps (chronomancy/spacetime-weaving.lua:164-207, added at :209-224) whose third-party trigger teleports whoever steps on either trap later (:179-194 teleportRandom at :183), so the landing/mover model does not describe it; the two prompts are distinguishable by cursor_type (:144 vs :152) and distance>=2 is checkable pre-commit, so neither is the blocker'},
    -- R2-REV-03 (rev2, DO_NOT_MERGE withdrawal): the R2 "declared
    -- interchangeable group" admission is WITHDRAWN. The curated proof claimed
    -- the prompts were semantically equivalent, but the native action rolls
    -- spellCrit SEPARATELY immediately before EACH projectile
    -- (spells/stone.lua:41-46,48-52,54-56; gifts/dwarven-nature.lua:37-42,44-47,49-52)
    -- and spellCrit does `rng.percent(chance)`
    -- (modules/tome/class/interface/Combat.lua:2012-2032), so every prompt
    -- position consumes a DISTINCT random crit outcome. Exchanging which answer
    -- belongs to which missile can exchange a crit and a non-crit between two
    -- different targets — an observable damage/kill difference. Shared base
    -- damage/projectile/damage-type does NOT establish interchangeability, and
    -- the prompts themselves are indistinguishable, so the executor cannot even
    -- pin an answer to a position it can name. That is a plugin-completeness
    -- boundary, never a strategy judgement: the tactic stays legal for a player.
    {talent='T_EARTHEN_MISSILES',scope='any',missing='nondeterministic_prompt_outcome',
        reason='the three bolt prompts are indistinguishable AND each carries an independent random crit outcome: the native action calls self:spellCrit(damage) separately before EACH projectile (spells/stone.lua:41-46,48-52,54-56) and spellCrit does rng.percent(chance) (modules/tome/class/interface/Combat.lua:2012-2032), so exchanging which answer belongs to which missile can exchange a crit and a non-crit between targets — the answers are not interchangeable and the plugin cannot execute the program honestly'},
    {talent='T_DWARVEN_HALF_EARTHEN_MISSILES',scope='any',missing='nondeterministic_prompt_outcome',
        reason='the three bolt prompts are indistinguishable AND each carries an independent random crit outcome: the native action calls self:spellCrit(damage) separately before EACH projectile (gifts/dwarven-nature.lua:37-42,44-47,49-52; the spec also sets friendlyfire=false,friendlyblock=false at :34/:41/:49) and spellCrit does rng.percent(chance) (modules/tome/class/interface/Combat.lua:2012-2032), so exchanging which answer belongs to which missile can exchange a crit and a non-crit between targets — the answers are not interchangeable and the prompts carry no positional signature to bind them'},
    {talent='*',scope='any',missing='moving_or_swapping_another_actor',
        reason='typed multi-actor destination/effect semantics are not implemented'},
}

function M.entry(talent) return M.ENTRIES[talent] end
function M.supported(talent) return talent~=nil and M.ENTRIES[talent]~=nil end

-- Every distinct target-request sequence a movement adapter can resolve to. A
-- variant matrix has one sequence per executable branch; a static adapter has
-- exactly one. Used by the pure policy validator, which cannot read runtime
-- state and therefore accepts a plan that matches any declared branch.
function M.requestSequences(entry)
    local movement=entry and entry.movement
    if type(movement)~='table' then return {} end
    if movement.variants then
        local out={}
        for _,variant in ipairs(movement.variants) do
            if variant.movement and type(variant.movement.target_requests)=='table' then
                out[#out+1]=variant.movement.target_requests
            elseif variant.unsupported and type(variant.unsupported.requests)=='table' then
                -- A known but unimplemented branch still declares its request
                -- sequence, so a policy using the S2 shape validates statically
                -- and then gets the typed capability reason at plan time.
                for _,requests in ipairs(variant.unsupported.requests) do
                    out[#out+1]=requests
                end
            end
        end
        return out
    end
    if type(movement.target_requests)=='table' then return {movement.target_requests} end
    return {}
end
function M.isSustain(talent)
    local entry=M.ENTRIES[talent]
    return entry~=nil and entry.kind=='sustain'
end

-- Components that can affect an actor, in evaluation order (ground last).
function M.effectComponents(entry)
    local out={}
    for _,component in ipairs(entry and entry.components or {}) do
        if component.phase~='cursor' then out[#out+1]=component end
    end
    return out
end

-- Distinct conditional variants declared by an entry: `{when, components}`.
function M.variants(entry)
    local groups={}
    for _,component in ipairs(entry and entry.components or {}) do
        local key=component.when and (component.when.kind..':'..tostring(component.when.id or component.when.at_least or component.when.below)) or 'always'
        local group=groups[key]
        if not group then
            group={when=component.when or {kind='always'},components={}}
            groups[key]=group
            groups[#groups+1]=group
        end
        group.components[#group.components+1]=component
    end
    return groups
end

-- Public capability summary, derived from the canonical components so it can
-- never disagree with the guard's source of truth.
function M.summary()
    local talents={}
    for talent,entry in pairs(M.ENTRIES) do
        local compat=M.compat(entry)
        talents[#talents+1]={talent=talent,kind=entry.kind,target=entry.target,
            delivery=compat.delivery,shape=compat.shape,range=compat.range,radius=compat.radius,
            resource=entry.resource,selffire=compat.selffire,friendlyfire=compat.friendlyfire,
            friendlyfire_risk=compat.friendlyfire_risk,
            has_ground=compat.ground~=nil,has_secondary=compat.secondary~=nil}
    end
    table.sort(talents,function(a,b) return a.talent<b.talent end)
    return {schema=M.SCHEMA,adapter_version=M.VERSION,game_version=M.GAME_VERSION,
        source_schema=Sources.schema,unsupported=M.UNSUPPORTED,talents=talents}
end

-- Derived compatibility view: a conservative flattening of the canonical
-- components for capability reporting and validators. It is never the guard's
-- input. `M.compat(entry)` guarantees the summary and validators agree with
-- the components.
local SHAPE_ORDER={widebeam=6,cone=5,ball=4,beam=3,bolt=2,hit=1,melee=0}
function M.compat(entry)
    if not entry then return nil end
    local primary
    local shape,delivery,selffire,friendlyfire
    local ground,secondary
    for _,component in ipairs(entry.components or {}) do
        if component.phase=='ground' then ground=component end
        if component.phase=='secondary' then secondary=component end
        if component.phase=='instant' or component.phase=='projectile' or component.phase=='melee' then
            if not primary then primary=component end
            local order=SHAPE_ORDER[component.shape] or 0
            if not shape or order>(SHAPE_ORDER[shape] or 0) then shape=component.shape end
            if component.delivery=='projectile' then delivery='projectile'
            elseif component.delivery=='attackTarget' then delivery=delivery or 'attackTarget'
            elseif not delivery then delivery='project' end
            local sf=component.selffire
            if type(sf)=='table' then sf='unknown' end
            if sf~=nil and (selffire==nil or (tonumber(sf) or 100)>(tonumber(selffire) or 0)) then selffire=sf end
            local ff=component.friendlyfire
            if type(ff)=='table' then ff='unknown' end
            if ff~=nil and (friendlyfire==nil or (tonumber(ff) or 100)>(tonumber(friendlyfire) or 0)) then friendlyfire=ff end
        end
    end
    local risk='none'
    if selffire~=0 or friendlyfire~=0 then
        if shape=='beam' or shape=='bolt' or shape=='widebeam' then risk='line'
        elseif shape=='ball' or shape=='cone' then risk='area' end
    end
    return {shape=shape,delivery=delivery,range=entry.range,radius=entry.radius,
        selffire=selffire or 0,friendlyfire=friendlyfire or 0,friendlyfire_risk=risk,
        cursor=entry.cursor,ground=ground,secondary=secondary,union=entry.union,
        components=entry.components,primary=primary}
end

M.HOSTILE_SELECTORS={nearest_hostile=true,lowest_hp_hostile=true,
    highest_rank_hostile=true,most_dangerous_hostile=true}
M.SELF_SELECTORS={self=true}
M.ACTIONS={
    use_talent={kind='talent'},
    attack={kind='attack'},
    move={kind='movement',action='move'},
    wait={kind='utility'},
    rest={kind='native_activity',activity='rest',default_max_turns=1000},
    auto_explore={kind='native_activity',activity='auto_explore'},
    change_level={kind='native_activity',activity='change_level',default_enabled=false},
}
function M.actionSupported(action) return action~=nil and M.ACTIONS[action]~=nil end

function M.verify(policy)
    local errors={}
    -- Checklist A (BND-REV-01): `policy.rules`/`policy.sustains` are caller data;
    -- only a dense+closed list is iterated. A malformed list is a typed error at
    -- this ingress — never a truncated prefix silently verified as complete (a
    -- sparse `policy.rules` with a hidden tail rule used to pass verify whole).
    local rules,ruleCount=nil,0
    if type(policy)=='table' and policy.rules~=nil then
        local dense,count=Json.denseArray(policy.rules)
        if not dense then
            return nil,{{path='rules',code='invalid_rules',cause=count}}
        end
        rules,ruleCount=policy.rules,count
    end
    local sustains,sustainCount=nil,0
    if type(policy)=='table' and policy.sustains~=nil then
        local dense,count=Json.denseArray(policy.sustains)
        if not dense then
            return nil,{{path='sustains',code='invalid_sustains',cause=count}}
        end
        sustains,sustainCount=policy.sustains,count
    end
    for index=1,ruleCount do
        local rule=rules[index]
        local action=rule['then'] and rule['then'].action
        local path='rules['..index..']'
        if action~=nil and not M.ACTIONS[action] then
            errors[#errors+1]={path=path..'.then.action',code='unsupported_action'}
        end
        local entry=rule['then'] and rule['then'].talent and M.ENTRIES[rule['then'].talent] or nil
        if entry then
            local selector=rule['then'].target or (policy.targeting and policy.targeting.default)
            -- MFT-REV-03 (Option A): an actor step selector is the effective
            -- binding when the action/default selector is absent, so the
            -- self/hostile consistency check honours it.
            if selector==nil and type(rule['then'].target_plan)=='table' then
                -- Checklist A: the plan is caller-supplied policy data; only a
                -- dense/closed list has a trustworthy actor step (a sparse list
                -- must not resolve a selector out of its `ipairs` prefix).
                local dense,count=Json.denseArray(rule['then'].target_plan,1)
                if dense then
                    for index=1,count do
                        local step=rule['then'].target_plan[index]
                        if step.request=='actor' and step.selector~=nil then
                            selector=step.selector
                            break
                        end
                    end
                end
            end
            -- A no-target movement request (position/relative/native_random) needs
            -- no actor selector; the plugin must not invent a self requirement.
            local destination=rule['then'].destination
            local no_target_move=entry.kind=='movement' and type(destination)=='table'
                and (destination.selector=='position' or destination.selector=='relative'
                    or destination.selector=='native_random')
            if entry.target=='self' and selector~=nil and not M.SELF_SELECTORS[selector]
                and not no_target_move then
                errors[#errors+1]={path=path,code='selector_not_self_only',talent=rule['then'].talent}
            end
            if entry.target=='hostile' and selector~=nil and not M.HOSTILE_SELECTORS[selector]
                and not no_target_move then
                errors[#errors+1]={path=path,code='selector_not_hostile',talent=rule['then'].talent}
            end
            -- MFT-REV-03: an explicit ordered target plan must match the
            -- source-pinned movement adapter's request sequence exactly.
            local plan=rule['then'].target_plan
            local movement=entry.kind=='movement' and entry.movement or nil
            if type(plan)=='table' then
                -- Checklist A: the plan is caller-supplied, so validate it dense
                -- and closed BEFORE the `#`/index reads below. A malformed plan
                -- is `invalid_target_plan` (its own typed shape fault), never
                -- measured as a shorter complete plan.
                local dense,planCount=Json.denseArray(plan,1)
                if not dense then
                    errors[#errors+1]={path=path..'.then.target_plan',code='invalid_target_plan'}
                else
                    local sequences=M.requestSequences(entry)
                    if movement==nil or #sequences==0 then
                        errors[#errors+1]={path=path..'.then.target_plan',
                            code='target_plan_not_supported',talent=rule['then'].talent}
                    else
                        -- A variant matrix may declare several executable request
                        -- sequences; the static validator cannot read runtime state,
                        -- so a plan is valid when it matches any declared sequence
                        -- exactly (same length, same kinds, consistent selectors).
                        local matched=false
                        local selectorMismatch=nil
                        for _,expected in ipairs(sequences) do
                            local expectedDense,expectedCount=Json.denseArray(expected,1)
                            if expectedDense and planCount==expectedCount then
                                local stepOk=true
                                local mismatch=nil
                                for step=1,planCount do
                                    if plan[step].request~=expected[step] then stepOk=false break end
                                    if expected[step]=='actor' and plan[step].selector~=nil
                                        and selector~=nil and plan[step].selector~=selector then
                                        stepOk=false
                                        mismatch={path=path..'.then.target_plan['..step..'].selector',
                                            code='target_plan_selector_mismatch',
                                            expected=selector,got=plan[step].selector}
                                        break
                                    end
                                end
                                if stepOk then matched=true break end
                                if mismatch and selectorMismatch==nil then selectorMismatch=mismatch end
                            end
                        end
                        if not matched then
                            local expectedCount=#sequences==1
                                and select(2,Json.denseArray(sequences[1],1)) or nil
                            if selectorMismatch then
                                errors[#errors+1]=selectorMismatch
                            elseif expectedCount and planCount~=expectedCount then
                                errors[#errors+1]={path=path..'.then.target_plan',
                                    code='target_plan_mismatch',
                                    expected=table.concat(sequences[1],','),got=planCount}
                            else
                                errors[#errors+1]={path=path..'.then.target_plan',
                                    code='target_plan_mismatch',
                                    expected=#sequences==1 and table.concat(sequences[1],',')
                                        or 'one_of_declared_variants'}
                            end
                        end
                    end
                end
            end
        elseif rule['then'] and rule['then'].action=='use_talent' then
            errors[#errors+1]={path=path,code='unsupported_talent',talent=rule['then'].talent}
        end
    end
    for index=1,sustainCount do
        local sustain=sustains[index]
        if not M.isSustain(sustain.talent) then
            errors[#errors+1]={path='sustains['..index..']',code='not_a_sustain',talent=sustain.talent}
        end
    end
    if #errors==0 then return true end
    return nil,errors
end

return M
