-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local previous_useTalent=_M.useTalent
local function instrumented(self, id, who, force_level, ignore_cd, force_target, silent, no_confirm)
	who = who or self
	local ab, ret = _M.talents_def[id]
	assert(ab, "trying to use talent "..tostring(id).." but it is not defined")

	self.talent_error = nil
	local cancel = false
	local co, success, err
	
	local msg, line

	local old_level, old_target, new_target = nil, nil, nil
	local function prepareUse()
		-- Stub some stuff
		if force_level then old_level = who.talents[id] end
		if ab.mode == "activated" then
			if ab.onAIGetTarget and not who.player then old_target = rawget(who, "getTarget"); new_target = function() return ab.onAIGetTarget(self, ab) end end
			if force_target and not old_target then old_target = rawget(who, "getTarget"); new_target = function(a) return force_target.x, force_target.y, not force_target.__no_self and force_target end end
		end
		if new_target then who.getTarget = new_target end
		if force_level then who.talents[id] = force_level end
	end
	local function finishUse()
		if new_target then who.getTarget = old_target end
		if force_level then who.talents[id] = old_level end
	end

	if ab.mode == "activated" and ab.action then
		if self:isTalentCoolingDown(ab) and not ignore_cd then
			game.logPlayer(who, "%s is still on cooldown for %d turns.", ab.name:capitalize(), math.ceil(self.talents_cd[ab.id]))
			return false
		end
		co = Tracker.createBody(function() -- coroutine to run activated talent code
			if cancel then
				success = false
				return false
			end
			
			if not self:preUseTalent(ab, silent) then return false end
			
			msg, line = game.logNewest()
			if not silent then self:logTalentMessage(ab) end
			
			self:setCurrentTalentMode("active", ab.id)
			prepareUse()
			local ok, ret, special = xpcall(function() return ab.action(who, ab) end, debug.traceback)
			finishUse()
			self:setCurrentTalentMode(nil)
			self.__talent_running = nil
			if not ok then self:onTalentLuaError(ab, ret) error(ret) end

			if not ret and self._silent_talent_failure then -- remove messages generated by failed talent
				local msg, newline = game.logNewest()
				if newline ~= line then game.logRollback(line) end
			end

			if not self:postUseTalent(ab, ret, silent) then return false end

			-- Everything went ok? then start cooldown if any
			if not ignore_cd and (not special or not special.ignore_cd) then self:startTalentCooldown(ab) end
			if ab.post_action then ab.post_action(who, ab) end
			return ret
		end)
	elseif ab.mode == "sustained" and ab.activate and ab.deactivate then
		if self:isTalentCoolingDown(ab) and not ignore_cd then
			game.logPlayer(who, "%s is still on cooldown for %d turns.", ab.name:capitalize(), math.ceil(self.talents_cd[ab.id]))
			return false
		end
		if ignore_cd == "ignore_check_only" then ignore_cd = nil end
		co = Tracker.createBody(function() -- coroutine to run sustainable talent code
			if cancel then
				success = false
				return false
			end
			if not self:preUseTalent(ab, silent) then return false end
			msg, line = game.logNewest()
			if not silent then self:logTalentMessage(ab) end
			
			local ok, ret, special
			if not self.sustain_talents[id] then -- activating
				if self.deactivating_sustain_talent == ab.id then return end
				self:setCurrentTalentMode("active", ab.id)
				prepareUse()
				ok, ret, special = xpcall(function() return ab.activate(who, ab) end, debug.traceback)
				finishUse()
				self:setCurrentTalentMode(nil)
				if not ok then self:onTalentLuaError(ab, ret) error(ret) end
				if ret == true then ret = {} end -- fix for badly coded talents
				if ret then ret.name = ret.name or ab.name end

				if not ret and self._silent_talent_failure then -- remove messages generated by failed talent
					local msg, newline = game.logNewest()
					if newline ~= line then game.logRollback(line) end
				end

				if not self:postUseTalent(ab, ret, silent) then return false end

				self.sustain_talents[id] = ret

				if ab.sustain_lists then
					local lists = ab.sustain_lists
					if 'table' ~= type(lists) then lists = {lists} end
					for _, list in ipairs(lists) do
						if 'table' == type(list) then
							list = table.getTable(self, unpack(list))
						else
							list = table.getTable(self, list)
						end
						table.insert(list, id)
					end
				end
				if ab.post_action then ab.post_action(who, ab) end
			else -- deactivating
				if self.deactivating_sustain_talent == ab.id then return end

				local p = self.sustain_talents[id]
				if p and type(p) == "table" and p.__tmpvals then
					for i = 1, #p.__tmpvals do
						self:removeTemporaryValue(p.__tmpvals[i][1], p.__tmpvals[i][2])
					end
				end
				p.__tmpvals = nil
				if p and type(p) == "table" and p.__tmpparticles then
					for i = 1, #p.__tmpparticles do
						self:removeParticles(p.__tmpparticles[i])
					end
				end
				p.__tmpparticles = nil
				self:setCurrentTalentMode("active", ab.id)
				prepareUse()
				ok, ret, special = xpcall(function() return ab.deactivate(who, ab, p) end, debug.traceback)
				finishUse()
				self:setCurrentTalentMode(nil)
				if not ok then self:onTalentLuaError(ab, ret) error(ret) end
				
				if not ret and self._silent_talent_failure then -- remove messages generated by failed talent
					local msg, newline = game.logNewest()
					if newline ~= line then game.logRollback(line) end
				end

				self.deactivating_sustain_talent = ab.id
				if not self:postUseTalent(ab, ret, silent) then self.deactivating_sustain_talent = nil return false end
				self.deactivating_sustain_talent = nil

				-- Everything went ok? then start cooldown if any
				if not ignore_cd then self:startTalentCooldown(ab) end
				self.sustain_talents[id] = nil

				if ab.sustain_lists then
					local lists = ab.sustain_lists
					if 'table' ~= type(lists) then lists = {lists} end
					for _, list in ipairs(lists) do
						if 'table' == type(list) then
							list = table.getTable(self, unpack(list))
						else
							list = table.getTable(self, list)
						end
						table.removeFromList(list, id)
					end
				end
				if ab.post_action then ab.post_action(who, ab) end
			end
			return ret
		end)
	else
		print("[useTalent] Attempt to use non activated or sustainable talent: "..id.." :: "..ab.name.." :: "..ab.mode)
	end
	if co then -- talent is usable and has passed checks
		local co_wrapper = coroutine.create(function() -- coroutine for talent interface
			success = true
			local ok
			while success do
				self.__talent_running = ab
				ok, ret = coroutine.resume(co) -- ret == error or return value from co
				success = success and ok
				self.__talent_running = nil
				if ok and coroutine.status(co) == "dead" then -- coroutine terminated normally
					if success and not ret then -- talent failed
						print("[useTalent] TALENT FAILED:", ab.id, "for", self.name, self.uid, success)
					--game.log("#ORANGE# %s TALENT USE FAILED [%s (silent_failure:%s at (%s, %s)]", ab.id, self.name, self._silent_talent_failure, self.x, self.y) -- debugging
					end
					return ret
				end
				if ret then error(ret) end --propagate error
				coroutine.yield()
			end
		end)
		if not no_confirm and self:isTalentConfirmable(ab) then
			local abname = game:getGenericTextTiles(ab)..tostring(self:getTalentDisplayName(ab))
			require "engine.ui.Dialog":yesnoPopup(_t"Talent Use Confirmation", ("Use %s?"):tformat(abname),
			function(quit)
				if quit ~= false then
					cancel = true
				end
				success, ret = coroutine.resume(co_wrapper)
				if not success and ret then -- talent code error
					self:onTalentLuaError(ab, ret)
					--print("useTalent:", debug.traceback(co_wrapper), '\n')
					error(ret)
				end
			end,
			_t"Cancel",_t"Continue")
		else
			success, ret = coroutine.resume(co_wrapper) -- cancel checked in coroutine
		end
		-- Cleanup in case we coroutine'd out
		self.__talent_running = nil
		if not success and ret then -- talent code error
			self:onTalentLuaError(ab, ret)
			--print("useTalent:", debug.traceback(co_wrapper), '\n')
			error(ret)
		end
	end
	self.changed = true
	
	return ret -- return value from successfully used talent
end
function _M:useTalent(id,...)
    if not Tracker.current() then return previous_useTalent(self,id,...) end
    return Tracker.call(self,id,instrumented,...)
end
Compat.register('useTalent',_M.useTalent,previous_useTalent,'/engine/interface/ActorTalents.lua','d3dbdbffd0df8ac45baba738b344b077')
return _M
