-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local Interactions=require 'mod.mcp_bridge.Interactions'
local previous_targetGetForPlayer=_M.targetGetForPlayer
local function instrumented(self, typ)
	if self.target.forced then return unpack(self.target.forced) end
	if coroutine.running() and typ then
		local msg
		self.target_no_start_scan = nil
		if type(typ) == "string" then msg, typ = typ, nil
		elseif type(typ) == "table" then
			if typ.default_target then
				self.target.target.entity = typ.default_target
				self.target_no_start_scan = true
			end
			msg = typ.msg
		end
		self:targetMode("exclusive", msg, coroutine.running(), typ)
		if typ.nowarning then self.target_warning = false end
		if not Tracker.current() and self.target.target.x and config.settings.auto_accept_target and not typ.immediate_keys and (not typ.nolock or typ.can_autoaccept) and (not typ.nowarning or typ.can_autoaccept) and (not typ.no_restrict or typ.can_autoaccept) then
			self.target_co = nil
			self:targetMode(false, false) self.tooltip_x, self.tooltip_y = nil, nil
			return self.target.target.x, self.target.target.y, self.target.target.entity
		end
		if typ.immediate_keys then self.target_style = "immediate" end
		if typ.nolock then self.target_style = "free" end
		Interactions.openTarget(self,typ)
		return coroutine.yield()
	end
	return self.target.target.x, self.target.target.y, self.target.target.entity
end
function _M:targetGetForPlayer(...)
    if not Tracker.current() then return previous_targetGetForPlayer(self,...) end
    return instrumented(self,...)
end
Compat.register('targetGetForPlayer',_M.targetGetForPlayer,previous_targetGetForPlayer,'/engine/interface/GameTargeting.lua','198ce5213e4dc8218730c64be53ee6fe')
local previous_targetMode=_M.targetMode
function _M:targetMode(v,...)
    local owner=Tracker.current() or Tracker.forCoroutine(self.target_co)
    if not owner then return previous_targetMode(self,v,...) end
    if not v then Interactions.closeTarget(self) end
    return Tracker.scope(owner,previous_targetMode,self,v,...)
end
Compat.register('targetMode',_M.targetMode,previous_targetMode,'/engine/interface/GameTargeting.lua','198ce5213e4dc8218730c64be53ee6fe')
return _M
