-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local NativeTasks=require 'mod.mcp_bridge.NativeTasks'
local previous_restInit=_M.restInit
function _M:restInit(...)
    return NativeTasks.start(self,previous_restInit,...)
end
Compat.register('restInit',_M.restInit,previous_restInit,'/engine/interface/PlayerRest.lua','fa26d54ed2197f5ba4a2da6546c66ad5')
local previous_restStop=_M.restStop
function _M:restStop(...)
    return NativeTasks.finish(self,previous_restStop,...)
end
Compat.register('restStop',_M.restStop,previous_restStop,'/engine/interface/PlayerRest.lua','fa26d54ed2197f5ba4a2da6546c66ad5')
return _M
