-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native Chat choices and page construction; no chat-data callbacks are interpreted here.
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local Interactions=require 'mod.mcp_bridge.Interactions'
local Chat=require 'engine.Chat'
local Dialog=require 'engine.dialogs.Chat'
local invoke=Chat.invoke
local function staffAllowed()
    return type(config)=='table' and type(config.settings)=='table' and type(config.settings.tome_mcp_bridge)=='table'
        and config.settings.tome_mcp_bridge.allow_command_staff==true
end
function Chat:invoke(...)
    local runtime=package.loaded['mod.mcp_bridge.Runtime']
    local owner=Tracker.current() or type(runtime)=='table' and runtime.nativeUIOwner and runtime.nativeUIOwner(game)
    -- The command-staff chat resumes its own coroutine from a dialog action;
    -- scoping it to the tracker body finishes the invocation early and
    -- deadlocks the native resume. Run it detached when explicitly allowed.
    if owner and owner.talent_id=='T_COMMAND_STAFF' and staffAllowed() then return invoke(self,...) end
    if owner and Compat.available('Chat.invoke') then return Tracker.scope(owner,invoke,self,...) end
    return invoke(self,...)
end
Compat.register('Chat.invoke',Chat.invoke,invoke,'/engine/Chat.lua','3fb98c9672d8a94dd486e4f7b2ee1f9b')
Compat.register('Chat.get',Chat.get,Chat.get,'/engine/Chat.lua','3fb98c9672d8a94dd486e4f7b2ee1f9b')
local init=Dialog.init
function Dialog:init(...)
    local result=init(self,...)
    Interactions.openChat(self)
    return result
end
Compat.register('Chat.init',Dialog.init,init,'/engine/dialogs/Chat.lua','f8c502cdb14dddbce143c8b50dc64afe')
local regen=Dialog.regen
function Dialog:regen(...)
    local owner=Interactions.dialogOwner(self)
    local result=regen(self,...)
    Interactions.closeDialog(self)
    if owner then Interactions.exposeTop(owner) end
    return result
end
Compat.register('Chat.regen',Dialog.regen,regen,'/engine/dialogs/Chat.lua','f8c502cdb14dddbce143c8b50dc64afe')
Compat.register('Chat.use',Dialog.use,Dialog.use,'/engine/dialogs/Chat.lua','f8c502cdb14dddbce143c8b50dc64afe')
Compat.register('Chat.generateList',Dialog.generateList,Dialog.generateList,'/engine/dialogs/Chat.lua','f8c502cdb14dddbce143c8b50dc64afe')
Compat.register('Chat.resolveAuto',Dialog.resolveAuto,Dialog.resolveAuto,'/engine/dialogs/Chat.lua','f8c502cdb14dddbce143c8b50dc64afe')
Compat.register('Chat.makeUI',Dialog.makeUI,Dialog.makeUI,'/engine/dialogs/Chat.lua','f8c502cdb14dddbce143c8b50dc64afe')
