-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=require 'engine.ui.Dialog'
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local Interactions=require 'mod.mcp_bridge.Interactions'
local new=_M.new
local NativeTasks=require 'mod.mcp_bridge.NativeTasks'
local previous_yesnoPopup=_M.yesnoPopup
local function native_yesnoPopup(self, title, text, fct, yes_text, no_text, no_leave, escape, preexit_fct)
	local w, h = self.font:size(text)
	local d = new(title, 1, 1)

--	d.key:addBind("EXIT", function() game:unregisterDialog(d) fct(false) end)
	local ok = require("engine.ui.Button").new{text=yes_text or _t"Yes", fct=function() if preexit_fct then preexit_fct(true) end game:unregisterDialog(d) fct(true) end}
	local cancel = require("engine.ui.Button").new{text=no_text or _t"No", fct=function() if preexit_fct then preexit_fct(false) end game:unregisterDialog(d) fct(false) end}
	if not no_leave then d.key:addBind("EXIT", function() if preexit_fct then preexit_fct(escape) end game:unregisterDialog(d) fct(escape) end) end
	d:loadUI{
		{left = 3, top = 3, ui=require("engine.ui.Textzone").new{width=w+20, height=h+5, text=text}},
		{left = 3, bottom = 3, ui=ok},
		{right = 3, bottom = 3, ui=cancel},
	}
	d:setFocus(ok)
	d:setupUI(true, true)

	Interactions.openDialog(d,'dialog.confirm',title,text,{
		{label=yes_text or _t"Yes",apply=function() ok.fct() end},
		{label=no_text or _t"No",apply=function() cancel.fct() end},
	},not no_leave and function() d.key:triggerVirtual('EXIT') end or nil)
	game:registerDialog(d)
	return d
end
function _M:yesnoPopup(...)
    if not Tracker.current() or not Compat.available('yesnoPopup') then return previous_yesnoPopup(self,...) end
    return native_yesnoPopup(self,...)
end
Compat.register('yesnoPopup',_M.yesnoPopup,previous_yesnoPopup,'/engine/ui/Dialog.lua','ab40d81086fb92acffc6b817b979a8e1')
local previous_yesnoLongPopup=_M.yesnoLongPopup
local function native_yesnoLongPopup(self, title, text, w, fct, yes_text, no_text, no_leave, escape, preexit_fct)
	local d
	local ok = require("engine.ui.Button").new{text=yes_text or _t"Yes", fct=function() if preexit_fct then preexit_fct(true) end game:unregisterDialog(d) fct(true) end}
	local cancel = require("engine.ui.Button").new{text=no_text or _t"No", fct=function() if preexit_fct then preexit_fct(false) end game:unregisterDialog(d) fct(false) end}

	w = math.max(w + 20, ok.w + cancel.w + 10)

	d = new(title, w + 6, 1)

--	d.key:addBind("EXIT", function() game:unregisterDialog(d) fct(false) end)
	if not no_leave then d.key:addBind("EXIT", function() if preexit_fct then preexit_fct(escape) end game:unregisterDialog(d) fct(escape) end) end
	d:loadUI{
		{left = 3, top = 3, ui=require("engine.ui.Textzone").new{width=w, auto_height = true, text=text}},
		{left = 3, bottom = 3, ui=ok},
		{right = 3, bottom = 3, ui=cancel},
	}
	d:setFocus(ok)
	d:setupUI(false, true)

	Interactions.openDialog(d,'dialog.confirm',title,text,{
		{label=yes_text or _t"Yes",apply=function() ok.fct() end},
		{label=no_text or _t"No",apply=function() cancel.fct() end},
	},not no_leave and function() d.key:triggerVirtual('EXIT') end or nil)
	game:registerDialog(d)
	return d
end
function _M:yesnoLongPopup(...)
    if not Tracker.current() or not Compat.available('yesnoLongPopup') then return previous_yesnoLongPopup(self,...) end
    return native_yesnoLongPopup(self,...)
end
Compat.register('yesnoLongPopup',_M.yesnoLongPopup,previous_yesnoLongPopup,'/engine/ui/Dialog.lua','ab40d81086fb92acffc6b817b979a8e1')
local previous_listPopup=_M.listPopup
local function native_listPopup(self, title, text, list, w, h, fct, select_fct)
	local d = new(title, 1, 1)
	local desc = require("engine.ui.Textzone").new{width=w, auto_height=true, text=text, scrollbar=true}
	local l = require("engine.ui.List").new{width=w, height=h-16 - desc.h, list=list, fct=function() d.key:triggerVirtual("ACCEPT") end, select=function(item) if select_fct then select_fct(item) end end}
	d:loadUI{
		{left = 3, top = 3, ui=desc},
		{left = 3, top = 3 + desc.h + 3, ui=require("engine.ui.Separator").new{dir="vertical", size=w - 12}},
		{left = 3, bottom = 3, ui=l},
	}
	d.key:addBind("EXIT", function() if fct then fct() end game:unregisterDialog(d) end)
	d.key:addBind("ACCEPT", function() if list[l.sel].fct then list[l.sel].fct(list[l.sel]) return end if fct then fct(list[l.sel]) end game:unregisterDialog(d) end)
	d:setFocus(l)
	d:setupUI(true, true)
	Interactions.openDialog(d,'dialog.choice',title,text,nil,
		function() d.key:triggerVirtual('EXIT') end,l)
	game:registerDialog(d)
	return d
end
function _M:listPopup(...)
    if not Tracker.current() or not Compat.available('listPopup') then return previous_listPopup(self,...) end
    return native_listPopup(self,...)
end
Compat.register('listPopup',_M.listPopup,previous_listPopup,'/engine/ui/Dialog.lua','ab40d81086fb92acffc6b817b979a8e1')
local previous_simplePopup=_M.simplePopup
local function native_simplePopup(self, title, text, fct, no_leave, any_leave)
	local _, w = tostring(text):toTString():splitLines(game.w * 0.7, self.font)
	local d = new(title, 1, 1)
	d:loadUI{{left = 3, top = 3, ui=require("engine.ui.Textzone").new{width=w+10, auto_height=true, text=text}}}
	if not no_leave then
		d.key:addBind("EXIT", function() game:unregisterDialog(d) if fct then fct() end end)
		if any_leave then d.key:addCommand("__DEFAULT", function() game:unregisterDialog(d) if fct then fct() end end) end
		local close = require("engine.ui.Button").new{text=_t"Close", fct=function() d.key:triggerVirtual("EXIT") end}
		d:loadUI{no_reset=true, {hcenter = 0, bottom = 3, ui=close}}
		d:setFocus(close)
	end
	d:setupUI(true, true)
	if not NativeTasks.claimPopup(d) and not no_leave then
		Interactions.openNotice(d,'simplePopup',title,text)
	end
	game:registerDialog(d)
	return d
end
function _M:simplePopup(...)
    if not Tracker.current() or not Compat.available('simplePopup') then return previous_simplePopup(self,...) end
    return native_simplePopup(self,...)
end
Compat.register('simplePopup',_M.simplePopup,previous_simplePopup,'/engine/ui/Dialog.lua','ab40d81086fb92acffc6b817b979a8e1')
local previous_simpleLongPopup=_M.simpleLongPopup
local function native_simpleLongPopup(self, title, text, w, fct, no_leave, force_height)
	local _, th = self.font:size(title)
	local d = new(title, 1, 1)
	local max_h = force_height and force_height * game.h or 9999
	local textzone = require("engine.ui.Textzone").new{width=w+10, auto_height=true, scrollbar=true, text=text}
	if textzone.h > max_h then textzone.h = max_h
	else textzone.scrollbar = nil
	end
	d:loadUI{{left = 3, top = 3, ui=textzone}}
	if not no_leave then
		d.key:addBind("EXIT", function() game:unregisterDialog(d) if fct then fct() end end)
		local close = require("engine.ui.Button").new{text=_t"Close", fct=function() d.key:triggerVirtual("EXIT") end}
		d:loadUI{no_reset=true, {hcenter = 0, bottom = 3, ui=close}}
		d:setFocus(close)
	end
	d:setupUI(true, true)
	if not NativeTasks.claimPopup(d) and not no_leave then
		Interactions.openNotice(d,'simpleLongPopup',title,text)
	end
	game:registerDialog(d)
	return d
end
function _M:simpleLongPopup(...)
    if not Tracker.current() or not Compat.available('simpleLongPopup') then return previous_simpleLongPopup(self,...) end
    return native_simpleLongPopup(self,...)
end
Compat.register('simpleLongPopup',_M.simpleLongPopup,previous_simpleLongPopup,'/engine/ui/Dialog.lua','ab40d81086fb92acffc6b817b979a8e1')
local previous_simpleWaiter=_M.simpleWaiter
local function native_simpleWaiter(self, title, text, width, count, max)
	width = width or 400

	local _, th = self.font:size(title)
	local d = new(title, 1, 1)
	local max_h = 9999
	local textzone = require("engine.ui.Textzone").new{width=width+10, auto_height=true, scrollbar=true, text=text}
	if textzone.h > max_h then textzone.h = max_h
	else textzone.scrollbar = nil
	end
	local wait = require("engine.ui.Waiter").new{size=width, known_max=max}
	d:loadUI{
		{left = 3, top = 3, ui=textzone},
		{left = 3, bottom = 3, ui=wait},
	}
	d:setupUI(true, true)

	d.done = function(self) game:unregisterDialog(self) end
	d.timeout = function(self, secs, cb) wait:setTimeout(secs, function() cb() local done = self.done self.done = function()end done(self) end) end
	d.manual = function(self, ...) wait:manual(...) end
	d.manualStep = function(self, ...) wait:manualStep(...) end

	Interactions.claimSceneWaiter(d)
	game:registerDialog(d)

	core.wait.enable(count, wait:getWaitDisplay(d))

	return d
end
function _M:simpleWaiter(...)
    if not Tracker.current() or not Compat.available('simpleWaiter') then return previous_simpleWaiter(self,...) end
    return native_simpleWaiter(self,...)
end
Compat.register('simpleWaiter',_M.simpleWaiter,previous_simpleWaiter,'/engine/ui/Dialog.lua','ab40d81086fb92acffc6b817b979a8e1')
local previous_simpleWaiterTip=_M.simpleWaiterTip
local function native_simpleWaiterTip(self, title, text, tip, width, count, max)
	if not tip then return self:simpleWaiter(title, text, width, count, max) end

	width = width or 400

	local _, th = self.font:size(title)
	local d = new(title, 1, 1)
	local wait = require("engine.ui.Waiter").new{size=width, known_max=max}
	local textzone = require("engine.ui.Textzone").new{width=wait.w, auto_height=true, scrollbar=false, text=text}
	local tipzone = require("engine.ui.Textzone").new{width=wait.w, auto_height=true, scrollbar=false, text=tip}
	local split = require("engine.ui.Separator").new{dir="vertical", size=wait.w - 12}
	d:loadUI{
		{left = 3, top = 3, ui=textzone},
		{left = 3+6, top = 3+textzone.h, ui=split},
		{left = 3, top = 3+textzone.h+split.h, ui=tipzone},
		{left = 3, bottom = 3, ui=wait},
	}
	d:setupUI(true, true)

	d.done = function(self) game:unregisterDialog(self) end
	d.timeout = function(self, secs, cb) wait:setTimeout(secs, function() cb() local done = self.done self.done = function()end done(self) end) end
	d.manual = function(self, ...) wait:manual(...) end
	d.manualStep = function(self, ...) wait:manualStep(...) end

	Interactions.claimSceneWaiter(d)
	game:registerDialog(d)

	core.wait.enable(count, wait:getWaitDisplay(d))

	return d
end
function _M:simpleWaiterTip(...)
    if not Tracker.current() or not Compat.available('simpleWaiterTip') then return previous_simpleWaiterTip(self,...) end
    return native_simpleWaiterTip(self,...)
end
Compat.register('simpleWaiterTip',_M.simpleWaiterTip,previous_simpleWaiterTip,'/engine/ui/Dialog.lua','ab40d81086fb92acffc6b817b979a8e1')
return _M
