-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=require 'engine.Game'
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local previous_onTickEnd=_M.onTickEnd
function _M:onTickEnd(fn,name)
    if Compat.available('onTickEnd') then
        local runtime=package.loaded['mod.mcp_bridge.Runtime']
        local owner=Tracker.current() or type(runtime)=='table' and runtime.nativeUIOwner and runtime.nativeUIOwner(self)
        fn=Tracker.callback(self,fn,owner)
    end
    return previous_onTickEnd(self,fn,name)
end
Compat.register('onTickEnd',_M.onTickEnd,previous_onTickEnd,'/engine/Game.lua','6d2f1747a69e38a7ae478046a78d489c')
return _M
