-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native Player item use; preserve the original coroutine and cleanup.
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
return function(_M)
local previous_playerUseObject=_M.playerUseObject
local function native_playerUseObject(self, o, item, inven)
	local ret = o:use(self, nil, inven, item) or {}
	Tracker.itemResult(self,ret)
	if not ret.used then return end
	if ret.id then
		o:identify(true)
	end
	if ret.destroy then
		if o.multicharge and o.multicharge > 1 then
			o.multicharge = o.multicharge - 1
		else
			local _, del = self:removeObject(self:getInven(inven), item)
			if del then
				game.log("You have no more %s.", o:getName{no_count=true, do_color=true})
			else
				game.log("You have %s.", o:getName{do_color=true})
			end
			self:sortInven(self:getInven(inven))
		end
		return true
	end
end
function _M:playerUseObject(...)
    if not Tracker.current() or not Compat.available('playerUseObject') then return previous_playerUseObject(self,...) end
    return native_playerUseObject(self,...)
end
Compat.register('playerUseObject',_M.playerUseObject,previous_playerUseObject,'/mod/class/Player.lua','3cad1f6e18051479dc7ead3598098378')
local previous_playerUseItem=_M.playerUseItem
local function native_playerUseItem(self, object, item, inven)
	if self.no_inventory_access then return end
	if not game.zone or game.zone.wilderness then game.logPlayer(self, "You cannot use items on the world map.") return end

	local use_fct = function(o, inven, item)
		if not o then return end
		local co = Tracker.createBody(function()
			self.changed = true
			return self:playerUseObject(o, item, inven)
		end)
		local ok, ret = coroutine.resume(co)
		if not ok and ret then print(debug.traceback(co)) error(ret) end
		return true
	end

	if object and item then return use_fct(object, inven, item) end

	local titleupdator = self:getEncumberTitleUpdator(_t"Use object")
	self:showEquipInven(titleupdator(),
		function(o)
			return o:canUseObject()
		end,
		use_fct
	)
end
function _M:playerUseItem(object,item,inven)
    if not Tracker.current() or not Compat.available('playerUseItem') then return previous_playerUseItem(self,object,item,inven) end
    return Tracker.callItem(self,function(player) return native_playerUseItem(player,object,item,inven) end)
end
Compat.register('playerUseItem',_M.playerUseItem,previous_playerUseItem,'/mod/class/Player.lua','3cad1f6e18051479dc7ead3598098378')
end
