-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
Compat.register('object.use',_M.use,_M.use,'/mod/class/Object.lua','4487a19154bcacfc6b90b784e64226b2')
Compat.register('object.useObject',_M.useObject,_M.useObject,'/mod/class/Object.lua','4487a19154bcacfc6b90b784e64226b2')
Compat.register('object.canUseObject',_M.canUseObject,_M.canUseObject,'/mod/class/Object.lua','4487a19154bcacfc6b90b784e64226b2')
return _M
