-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
Compat.register('TomeChat.init',_M.init,_M.init,'/mod/dialogs/Chat.lua','25bb6bf9cf881358262d6a9a0bdeb0da')
Compat.register('TomeChat.makeUI',_M.makeUI,_M.makeUI,'/mod/dialogs/Chat.lua','25bb6bf9cf881358262d6a9a0bdeb0da')
return _M
