-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local Interactions=require 'mod.mcp_bridge.Interactions'
local previous_init=_M.init
function _M:init(...)
    local result=previous_init(self,...)
    if Tracker.current() and Compat.matches('QuestPopup.init',self.init) then
        Interactions.openNotice(self,'QuestPopup',self.title,Interactions.noticeText(self))
    end
    return result
end
Compat.register('QuestPopup.init',_M.init,previous_init,'/mod/dialogs/QuestPopup.lua','4322f56fee8392e18f78efb305f2b01b')
return _M
