-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local Interactions=require 'mod.mcp_bridge.Interactions'
local previous_init=_M.init
function _M:init(...)
    local result=previous_init(self,...)
    if Tracker.current() and Compat.matches('ShowEquipInven.use',self.use) then
        Interactions.openInventory(self,'ShowEquipInven')
    end
    return result
end
Compat.register('ShowEquipInven.init',_M.init,previous_init,'/mod/dialogs/ShowEquipInven.lua','c339c5dbd5ac49fc3421b41838c3f7df')
Compat.register('ShowEquipInven.use',_M.use,_M.use,'/mod/dialogs/ShowEquipInven.lua','c339c5dbd5ac49fc3421b41838c3f7df')
return _M
