-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local Interactions=require 'mod.mcp_bridge.Interactions'
local previous_init=_M.init
function _M:init(...)
    local result=previous_init(self,...)
    if Tracker.current() and Compat.matches('ShowInventory.use',self.use) then
        Interactions.openInventory(self,'ShowInventory')
    end
    return result
end
Compat.register('ShowInventory.init',_M.init,previous_init,'/mod/dialogs/ShowInventory.lua','f08e62800ea9972ce38d66996123ebad')
Compat.register('ShowInventory.use',_M.use,_M.use,'/mod/dialogs/ShowInventory.lua','f08e62800ea9972ce38d66996123ebad')
return _M
