-- GENERATED by tools/generate_native_seams.py; do not edit by hand.
-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.
local _M=loadPrevious(...)
local Tracker=require 'mod.mcp_bridge.InvocationTracker'
local Compat=require 'mod.mcp_bridge.NativeCompatibility'
local Interactions=require 'mod.mcp_bridge.Interactions'
local previous_init=_M.init
function _M:init(...)
    local result=previous_init(self,...)
    if Tracker.current() and Compat.matches('ShowLore.init',self.init) then
        Interactions.openNotice(self,'ShowLore',self.title,Interactions.noticeText(self))
    end
    return result
end
Compat.register('ShowLore.init',_M.init,previous_init,'/mod/dialogs/ShowLore.lua','d1ceca0d5567b4c34db6d1a0fd5d85de')
return _M
