#!/usr/bin/env python3
"""Generate narrow native method seams; fail on unexpected upstream structure.

Generated addon superloads keep the original method for non-MCP calls. Native
method bodies are reproduced from this checkout, with only the listed lifecycle
insertions. Source hashes gate compatibility at load time. No game core is edited.
"""
from pathlib import Path
import argparse
import hashlib
import re

ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = ROOT.parents[2]
ENGINE = WORKSPACE / 'game/engines/default/engine'


def configure(game_root: str | None = None) -> None:
    """Point the generator at a ToME source checkout (spec M0 --game-root)."""
    global WORKSPACE, ENGINE
    WORKSPACE = Path(game_root).resolve() if game_root else ROOT.parents[2]
    ENGINE = WORKSPACE / 'game/engines/default/engine'
    if not (ENGINE / 'interface/ActorTalents.lua').is_file():
        raise SystemExit(
            f'Native game source not found under {WORKSPACE}; pass --game-root /path/to/tome-source')



def method(text: str, name: str) -> str:
    match = re.search(rf'^function _M:{re.escape(name)}\(.*?\nend(?=\n)', text, re.M | re.S)
    if not match:
        raise ValueError(f'Native method missing: {name}')
    return match[0]


def replace_once(text: str, before: str, after: str, count: int = 1) -> str:
    assert text.count(before) == count, (before, text.count(before), count)
    return text.replace(before, after)


def header() -> str:
    return ('-- GENERATED by tools/generate_native_seams.py; do not edit by hand.\n'
            '-- Native code: Copyright (C) Nicolas Casalini, GPL-3.0-or-later.\n'
            'local _M=loadPrevious(...)\n'
            "local Tracker=require 'mod.mcp_bridge.InvocationTracker'\n"
            "local Compat=require 'mod.mcp_bridge.NativeCompatibility'\n")


def registration(name: str, path: str, digest: str) -> str:
    return f"Compat.register('{name}',_M.{name},previous_{name},'{path}','{digest}')\n"


def generate() -> dict[Path, str]:
    output = {}
    player_source=(WORKSPACE/'game/modules/tome/class/Player.lua').read_bytes()
    output[ROOT/'overload/mod/mcp_bridge/NativeManifest.lua']=(
        '-- GENERATED native compatibility manifest. MD5 is an engine compatibility checksum.\n'
        f"return {{player_md5='{hashlib.md5(player_source).hexdigest()}',\n"
        f"    game_md5='{hashlib.md5((WORKSPACE/'game/modules/tome/class/Game.lua').read_bytes()).hexdigest()}',\n"
        f"    companion_game_md5='{hashlib.md5((WORKSPACE/'game/addons/tome-battle-companion/superload/mod/class/Game.lua').read_bytes()).hexdigest()}',\n"
        f"    actor_fov_md5='{hashlib.md5((ENGINE/'interface/ActorFOV.lua').read_bytes()).hexdigest()}',\n"
        f"    map_md5='{hashlib.md5((ENGINE/'Map.lua').read_bytes()).hexdigest()}',\n"
        f"    actor_md5='{hashlib.md5((WORKSPACE/'game/modules/tome/class/Actor.lua').read_bytes()).hexdigest()}',\n"
        f"    entity_md5='{hashlib.md5((ENGINE/'Entity.lua').read_bytes()).hexdigest()}',\n"
        f"    resources_md5='{hashlib.md5((WORKSPACE/'game/modules/tome/data/resources.lua').read_bytes()).hexdigest()}',\n"
        f"    stats_md5='{hashlib.md5((ENGINE/'interface/ActorStats.lua').read_bytes()).hexdigest()}',\n"
        f"    combat_md5='{hashlib.md5((WORKSPACE/'game/modules/tome/class/interface/Combat.lua').read_bytes()).hexdigest()}'}}\n")
    text=("-- GENERATED by tools/generate_native_seams.py; do not edit by hand.\n"
          "-- Native Player item use; preserve the original coroutine and cleanup.\n"
          "local Tracker=require 'mod.mcp_bridge.InvocationTracker'\n"
          "local Compat=require 'mod.mcp_bridge.NativeCompatibility'\n"
          'return function(_M)\n')
    for name in ('playerUseObject','playerUseItem'):
        body=method(player_source.decode(),name)
        body=replace_once(body,f'function _M:{name}(',f'local function native_{name}(self, ')
        if name=='playerUseObject':
            body=replace_once(body,'\tlocal ret = o:use(self, nil, inven, item) or {}',
                '\tlocal ret = o:use(self, nil, inven, item) or {}\n\tTracker.itemResult(self,ret)')
            args='...';call='native_playerUseObject(self,...)'
        else:
            body=replace_once(body,'local co = coroutine.create(function()', 'local co = Tracker.createBody(function()')
            args='object,item,inven';call="Tracker.callItem(self,function(player) return native_playerUseItem(player,object,item,inven) end)"
        text+=f'local previous_{name}=_M.{name}\n'+body+'\n'
        text+=(f'function _M:{name}({args})\n'
               f"    if not Tracker.current() or not Compat.available('{name}') then return previous_{name}(self,{args}) end\n"
               f'    return {call}\nend\n')
        text+=registration(name,'/mod/class/Player.lua',hashlib.md5(player_source).hexdigest())
    output[ROOT/'overload/mod/mcp_bridge/NativeItemSeams.lua']=text+'end\n'
    object_source=(WORKSPACE/'game/modules/tome/class/Object.lua').read_bytes()
    text=header()
    for name in ('use','useObject','canUseObject'):
        text+=f"Compat.register('object.{name}',_M.{name},_M.{name},'/mod/class/Object.lua','{hashlib.md5(object_source).hexdigest()}')\n"
    output[ROOT/'superload/mod/class/Object.lua']=text+'return _M\n'
    source = (ENGINE / 'interface/ActorTalents.lua').read_text()
    digest = hashlib.md5(source.encode()).hexdigest()
    body = method(source, 'useTalent')
    body = replace_once(body, 'function _M:useTalent(', 'local function instrumented(self, ')
    body = replace_once(body, 'co = coroutine.create(function()', 'co = Tracker.createBody(function()', 2)
    text = header() + 'local previous_useTalent=_M.useTalent\n' + body + '\n'
    text += ('function _M:useTalent(id,...)\n'
             '    if not Tracker.current() then return previous_useTalent(self,id,...) end\n'
             '    return Tracker.call(self,id,instrumented,...)\nend\n')
    text += registration('useTalent', '/engine/interface/ActorTalents.lua', digest) + 'return _M\n'
    output[ROOT / 'superload/engine/interface/ActorTalents.lua'] = text

    source = (ENGINE / 'interface/GameTargeting.lua').read_text()
    digest = hashlib.md5(source.encode()).hexdigest()
    body = method(source, 'targetGetForPlayer')
    body = replace_once(body, 'function _M:targetGetForPlayer(', 'local function instrumented(self, ')
    body = replace_once(body, 'if self.target.target.x and config.settings.auto_accept_target',
                        'if not Tracker.current() and self.target.target.x and config.settings.auto_accept_target')
    body = replace_once(body, '\t\treturn coroutine.yield()',
                        '\t\tInteractions.openTarget(self,typ)\n\t\treturn coroutine.yield()')
    text = header() + "local Interactions=require 'mod.mcp_bridge.Interactions'\n"
    text += 'local previous_targetGetForPlayer=_M.targetGetForPlayer\n' + body + '\n'
    text += ('function _M:targetGetForPlayer(...)\n'
             '    if not Tracker.current() then return previous_targetGetForPlayer(self,...) end\n'
             '    return instrumented(self,...)\nend\n')
    text += registration('targetGetForPlayer', '/engine/interface/GameTargeting.lua', digest)
    text += ('local previous_targetMode=_M.targetMode\n'
             'function _M:targetMode(v,...)\n'
             '    local owner=Tracker.current() or Tracker.forCoroutine(self.target_co)\n'
             '    if not owner then return previous_targetMode(self,v,...) end\n'
             '    if not v then Interactions.closeTarget(self) end\n'
             '    return Tracker.scope(owner,previous_targetMode,self,v,...)\nend\n')
    text += registration('targetMode', '/engine/interface/GameTargeting.lua', digest) + 'return _M\n'
    output[ROOT / 'superload/engine/interface/GameTargeting.lua'] = text

    source = (ENGINE / 'Target.lua').read_text()
    digest = hashlib.md5(source.encode()).hexdigest()
    text = header()
    for name in ('setSpot', 'setDirFrom'):
        text += f'local previous_{name}=_M.{name}\n'
        text += registration(name, '/engine/Target.lua', digest)
    output[ROOT / 'superload/engine/Target.lua'] = text + 'return _M\n'

    source = (ENGINE / 'GameTurnBased.lua').read_text()
    digest = hashlib.md5(source.encode()).hexdigest()
    text = header() + 'local previous_turnBasedTick=_M.tick\n'
    text += ("function _M:tick(...)\n"
             "    local Runtime=require 'mod.mcp_bridge.Runtime'\n"
             "    if Runtime.holdsNativeInput(self) then\n"
             "        self.paused=true\n"
             "        engine.Game.tick(self)\n"
             "        if Runtime.holdsNativeInput(self) then self.paused=true\n"
             "        elseif self.player and self.player.energy and self.player.energy.value<self.energy_to_act then\n"
             "            self.paused=false\n"
             "        end\n"
             "        return\n"
             "    end\n"
             "    local result=previous_turnBasedTick(self,...)\n"
             "    if Runtime.holdsNativeInput(self) then self.paused=true end\n"
             "    return result\nend\n")
    text += f"Compat.register('turnBasedTick',_M.tick,previous_turnBasedTick,'/engine/GameTurnBased.lua','{digest}')\n"
    output[ROOT / 'superload/engine/GameTurnBased.lua'] = text + 'return _M\n'

    source = (ENGINE / 'Game.lua').read_bytes()
    digest = hashlib.md5(source).hexdigest()
    text = header().replace('local _M=loadPrevious(...)', "local _M=require 'engine.Game'")
    text += ('local previous_onTickEnd=_M.onTickEnd\n'
             'function _M:onTickEnd(fn,name)\n'
             "    if Compat.available('onTickEnd') then\n"
             "        local runtime=package.loaded['mod.mcp_bridge.Runtime']\n"
             "        local owner=Tracker.current() or type(runtime)=='table' and runtime.nativeUIOwner and runtime.nativeUIOwner(self)\n"
             "        fn=Tracker.callback(self,fn,owner)\n"
             "    end\n"
             '    return previous_onTickEnd(self,fn,name)\nend\n')
    text += registration('onTickEnd', '/engine/Game.lua', digest)
    output[ROOT / 'overload/mod/mcp_bridge/NativeGameSeams.lua'] = text + 'return _M\n'

    source=(ENGINE/'Chat.lua').read_bytes()
    chat_source=(ENGINE/'dialogs/Chat.lua').read_bytes()
    digest=hashlib.md5(chat_source).hexdigest()
    text=("-- GENERATED by tools/generate_native_seams.py; do not edit by hand.\n"
          "-- Native Chat choices and page construction; no chat-data callbacks are interpreted here.\n"
          "local Tracker=require 'mod.mcp_bridge.InvocationTracker'\n"
          "local Compat=require 'mod.mcp_bridge.NativeCompatibility'\n"
          "local Interactions=require 'mod.mcp_bridge.Interactions'\n"
          "local Chat=require 'engine.Chat'\n"
          "local Dialog=require 'engine.dialogs.Chat'\n"
          "local invoke=Chat.invoke\n"
          "local function staffAllowed()\n"
          "    return type(config)=='table' and type(config.settings)=='table' and type(config.settings.tome_mcp_bridge)=='table'\n"
          "        and config.settings.tome_mcp_bridge.allow_command_staff==true\n"
          "end\n"
          "function Chat:invoke(...)\n"
          "    local runtime=package.loaded['mod.mcp_bridge.Runtime']\n"
          "    local owner=Tracker.current() or type(runtime)=='table' and runtime.nativeUIOwner and runtime.nativeUIOwner(game)\n"
          "    -- The command-staff chat resumes its own coroutine from a dialog action;\n"
          "    -- scoping it to the tracker body finishes the invocation early and\n"
          "    -- deadlocks the native resume. Run it detached when explicitly allowed.\n"
          "    if owner and owner.talent_id=='T_COMMAND_STAFF' and staffAllowed() then return invoke(self,...) end\n"
          "    if owner and Compat.available('Chat.invoke') then return Tracker.scope(owner,invoke,self,...) end\n"
          "    return invoke(self,...)\nend\n"
          f"Compat.register('Chat.invoke',Chat.invoke,invoke,'/engine/Chat.lua','{hashlib.md5(source).hexdigest()}')\n"
          f"Compat.register('Chat.get',Chat.get,Chat.get,'/engine/Chat.lua','{hashlib.md5(source).hexdigest()}')\n"
          "local init=Dialog.init\n"
          "function Dialog:init(...)\n"
          "    local result=init(self,...)\n"
          "    Interactions.openChat(self)\n"
          "    return result\nend\n"
          f"Compat.register('Chat.init',Dialog.init,init,'/engine/dialogs/Chat.lua','{digest}')\n"
          "local regen=Dialog.regen\n"
          "function Dialog:regen(...)\n"
          "    local owner=Interactions.dialogOwner(self)\n"
          "    local result=regen(self,...)\n"
          "    Interactions.closeDialog(self)\n"
          "    if owner then Interactions.exposeTop(owner) end\n"
          "    return result\nend\n"
          f"Compat.register('Chat.regen',Dialog.regen,regen,'/engine/dialogs/Chat.lua','{digest}')\n")
    for name in ('use','generateList','resolveAuto','makeUI'):
        text+=f"Compat.register('Chat.{name}',Dialog.{name},Dialog.{name},'/engine/dialogs/Chat.lua','{digest}')\n"
    output[ROOT/'overload/mod/mcp_bridge/NativeChatSeams.lua']=text
    source=(WORKSPACE/'game/modules/tome/dialogs/Chat.lua').read_bytes()
    text=header()
    for name in ('init','makeUI'):
        text+=f"Compat.register('TomeChat.{name}',_M.{name},_M.{name},'/mod/dialogs/Chat.lua','{hashlib.md5(source).hexdigest()}')\n"
    output[ROOT/'superload/mod/dialogs/Chat.lua']=text+'return _M\n'

    source = (ENGINE / 'ui/Dialog.lua').read_text()
    digest = hashlib.md5(source.encode()).hexdigest()
    text = header().replace('local _M=loadPrevious(...)', "local _M=require 'engine.ui.Dialog'") + "local Interactions=require 'mod.mcp_bridge.Interactions'\nlocal new=_M.new\n"
    text += "local NativeTasks=require 'mod.mcp_bridge.NativeTasks'\n"
    for name in ('yesnoPopup', 'yesnoLongPopup', 'listPopup', 'simplePopup', 'simpleLongPopup', 'simpleWaiter', 'simpleWaiterTip'):
        body = method(source, name)
        body = replace_once(body, f'function _M:{name}(', f'local function native_{name}(self, ')
        if name in ('simpleWaiter', 'simpleWaiterTip'):
            seam = '\tInteractions.claimSceneWaiter(d)\n'
        elif name in ('simplePopup', 'simpleLongPopup'):
            seam = ("\tif not NativeTasks.claimPopup(d) and not no_leave then\n"
                    f"\t\tInteractions.openNotice(d,'{name}',title,text)\n\tend\n")
        elif name == 'listPopup':
            seam = ("\tInteractions.openDialog(d,'dialog.choice',title,text,nil,\n"
                    "\t\tfunction() d.key:triggerVirtual('EXIT') end,l)\n")
        else:
            seam = ("\tInteractions.openDialog(d,'dialog.confirm',title,text,{\n"
                    "\t\t{label=yes_text or _t\"Yes\",apply=function() ok.fct() end},\n"
                    "\t\t{label=no_text or _t\"No\",apply=function() cancel.fct() end},\n"
                    "\t},not no_leave and function() d.key:triggerVirtual('EXIT') end or nil)\n")
        body = replace_once(body, '\tgame:registerDialog(d)', seam + '\tgame:registerDialog(d)')
        text += f'local previous_{name}=_M.{name}\n' + body + '\n'
        text += (f'function _M:{name}(...)\n'
                 f"    if not Tracker.current() or not Compat.available('{name}') then return previous_{name}(self,...) end\n"
                 f'    return native_{name}(self,...)\nend\n')
        text += registration(name, '/engine/ui/Dialog.lua', digest)
    output[ROOT / 'overload/mod/mcp_bridge/NativeDialogSeams.lua'] = text + 'return _M\n'

    for dialog in ('QuestPopup', 'LorePopup', 'ShowLore'):
        path=f'/mod/dialogs/{dialog}.lua'
        source=(WORKSPACE/f'game/modules/tome/dialogs/{dialog}.lua').read_text()
        digest=hashlib.md5(source.encode()).hexdigest()
        text=header()+"local Interactions=require 'mod.mcp_bridge.Interactions'\n"
        if dialog=='LorePopup':
            # This native constructor registers itself, so ownership must be
            # installed before registration, with already-rendered native text.
            body=method(source,'init')
            body=replace_once(body,'function _M:init(', 'local function instrumented(self, ')
            body=replace_once(body,'\tgame:registerDialog(self)',
                "\tInteractions.openNotice(self,'LorePopup',self.title,text)\n\tgame:registerDialog(self)")
            text+=("local Dialog=require 'engine.ui.Dialog'\n"
                   "local EntityDisplay=require 'engine.ui.EntityDisplay'\n"
                   "local Image=require 'engine.ui.Image'\n"
                   'local previous_init=_M.init\n'+body+'\n'
                   'function _M:init(...)\n'
                   "    if not Tracker.current() or not Compat.matches('LorePopup.init',self.init) then return previous_init(self,...) end\n"
                   '    return instrumented(self,...)\nend\n')
        else:
            text+=('local previous_init=_M.init\n'
                   'function _M:init(...)\n'
                   '    local result=previous_init(self,...)\n'
                   f"    if Tracker.current() and Compat.matches('{dialog}.init',self.init) then\n"
                   f"        Interactions.openNotice(self,'{dialog}',self.title,Interactions.noticeText(self))\n"
                   '    end\n'
                   '    return result\nend\n')
        text+=f"Compat.register('{dialog}.init',_M.init,previous_init,'{path}','{digest}')\n"
        output[ROOT/f'superload/mod/dialogs/{dialog}.lua']=text+'return _M\n'

    source = (ENGINE / 'interface/PlayerRest.lua').read_text()
    digest = hashlib.md5(source.encode()).hexdigest()
    text = header() + "local NativeTasks=require 'mod.mcp_bridge.NativeTasks'\n"
    for name, seam in (('restInit','start'),('restStop','finish')):
        text += (f'local previous_{name}=_M.{name}\n'
                 f'function _M:{name}(...)\n'
                 f'    return NativeTasks.{seam}(self,previous_{name},...)\nend\n')
        text += registration(name, '/engine/interface/PlayerRest.lua', digest)
    output[ROOT / 'superload/engine/interface/PlayerRest.lua'] = text + 'return _M\n'
    for dialog in ('ShowInventory','ShowEquipInven'):
        path=f'/mod/dialogs/{dialog}.lua'
        source=(WORKSPACE/f'game/modules/tome/dialogs/{dialog}.lua').read_bytes()
        digest=hashlib.md5(source).hexdigest()
        text=header()+"local Interactions=require 'mod.mcp_bridge.Interactions'\n"
        text+=('local previous_init=_M.init\n'
               'function _M:init(...)\n'
               '    local result=previous_init(self,...)\n'
               f"    if Tracker.current() and Compat.matches('{dialog}.use',self.use) then\n"
               f"        Interactions.openInventory(self,'{dialog}')\n"
               '    end\n'
               '    return result\nend\n')
        text+=f"Compat.register('{dialog}.init',_M.init,previous_init,'{path}','{digest}')\n"
        text+=f"Compat.register('{dialog}.use',_M.use,_M.use,'{path}','{digest}')\n"
        output[ROOT/f'superload/mod/dialogs/{dialog}.lua']=text+'return _M\n'
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--game-root', default=None,
                        help='ToME source root with game/ (defaults to the enclosing checkout)')
    args = parser.parse_args()
    configure(args.game_root)
    for path, text in generate().items():
        if args.check:
            assert path.is_file() and path.read_text() == text, f'Native seam out of date: {path}'
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
        print(path.relative_to(ROOT))


if __name__ == '__main__':
    main()
